apiVersion: v1
data:
  client_id: {{ .Values.global.dcm.di.clientID | b64enc }}
  client_secret: {{ .Values.global.dcm.di.clientSecret | b64enc }}
kind: Secret
metadata:
  name: dcm-di-secret
  namespace: {{ .Release.Namespace }}
