{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "microservice.fullname" . }}
  labels:
{{ include "microservice.labels" . | indent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "microservice.fullname" . }}-role
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ "tls-credential", "mtls-credential", "mtls-credential-recovery" ]
    verbs: [ "get","update","watch" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    resourceNames: [ "vault-bootstrap" ]
    verbs: [ "list","get","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "microservice.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "microservice.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "microservice.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
