annotations:
  containerImages: |
    - oe-template-mgr-svc
    - busybox
    - oe-template-mgr-smoke-test
apiVersion: v2
appVersion: latest
description: A Helm chart for the Device Onboarding Template Service
name: hzp-oe-template-mgr
type: application
version: 0.1.0
