{{- $svc := .Values.svc -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.svc.name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ $svc.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/app: {{ .Values.svc.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
spec:
{{- if not .Values.svc.autoScaling.enabled }}
  replicas: {{ .Values.svc.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.svc.name }}
  template:
    metadata:
      annotations:
{{- tpl (toYaml .Values.svc.podAnnotations) . | replace "'" "" | nindent 8 }}
{{- if .Values.global.instrumentation.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ $svc.port }}"
{{- end }} 	
      labels:
        app.kubernetes.io/app: {{ .Values.svc.name }}
{{- tpl (toYaml .Values.svc.podLabels) . | replace "'" "" | nindent 8 }}
    spec:
      serviceAccountName: hzp-product-service-account
      securityContext:
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.svc $ )| trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.svc $ ) | trim | nindent 8 }}
      affinity: {{- include "pods.affinity" ( list .Values.svc $ ) | trim | nindent 8 }}
      initContainers:
        - name: init-eo-initialization
          image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
          imagePullPolicy: {{ .Values.svc.image.pullPolicy }}
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: EO_INIT_HOST
              value: "{{ .Values.svc.dependency.eoInitSvc.service.fullname }}"
            - name: EO_INIT_PORT
              value: "{{ .Values.svc.dependency.eoInitSvc.service.port }}"
          command:
            - sh
            - -c
            - |
              echo 'Waiting for eo-initialization Svc to become ready...'
              command="wget -S ${EO_INIT_HOST}:${EO_INIT_PORT}/admin/health/liveness 2>&1 | awk '/^  HTTP/{print $2}'"
              status=$(eval "$command")
              echo "status: $status"
              while [[ "$status" != *"HTTP/1.1 200"* ]]; do
                  sleep 2;
                  status=$(eval "$command")
                  echo "status: $status"
              done;
              echo 'Hzp-initialization OK ✓'
      containers:
# hzp-ese-svc listens on port 8082
        - image: {{ include "manifest.image.name" (dict "data" (index .Values.components .Values.ese.image.name ) "repo" .Values.global.repository) }}
          name: {{.Values.ese.name}}
          imagePullPolicy: {{ .Values.ese.image.pullPolicy }}
          env:
            - name: TARGET_ENV
              value: "{{ .Values.global.product.backendconnectivityenvironment }}"
            {{- toYaml .Values.ese.env | nindent 12 }}
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.ese.resources | nindent 12 }}
          volumeMounts:
            - name: ese-config
              mountPath: /opt/ese/etc/DefaultProperties.json
              subPath: DefaultProperties.json
            - name: machine-id
              mountPath: /etc/machine-id
              subPath: machine-id
            - name: ese-pvc
              mountPath: /opt/ese/var
            - name: hzp-shared-pvc
              mountPath: /data
# hzp-product-svc listens on port 8080
        - image: {{ include "manifest.image.name" (dict "data" (index .Values.components .Values.svc.image.name ) "repo" .Values.global.repository) }}
          {{ $_ := set .Values "iamProxyEntry" "/entrypoint.sh" }}
          {{tpl (toYaml .Values.global.iamProxy.commandDecorator) . | nindent 10 }}
          name: {{$svc.name}}
          imagePullPolicy: {{ $svc.image.pullPolicy }}
          resources:
            {{- toYaml .Values.svc.resources | nindent 12 }}
          env:
            - name: SIDECAR_INJECTED
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['hzp.iam.webhook']
            - name: ESE_ENDPT
              value: "http://localhost:8082/ese"
            - name: POD_NAMESPACE
              value: "{{.Release.Namespace}}"
            - name: no_proxy
              value: "*.*"
            - name: APP_PORT
              value: "{{ $svc.port }}"
            - name: ENABLE_REMOTE
              value: "{{ .Values.global.ingress.fqdn }}"
            - name: EVENTING_TYPE
              value: {{ .Values.global.message.type | quote }}
            - name: NATS_URL
              value: {{ tpl .Values.global.message.url . | quote }}
            - name: NATS_SERVER_MONITORING_URL
              value: "http://jetstream.{{ .Release.Namespace }}.svc.cluster.local:8222/healthz"
            - name: INGRESS_FQDN
              value: {{ .Values.global.ingress.fqdn }}
            - name: EO_NAME
              value: {{ .Values.global.eoName }}
            - name: S3_URL
              value: {{ tpl .Values.global.s3.url . | quote }}
            - name: SEAWEEDFS_S3_URL  # For backwards-compatibility.
              value: {{ tpl .Values.global.s3.url . | quote }}
            - name: S3_REGION
              value: {{ .Values.global.s3.region | default "us-east-1" }}
            - name: S3_BUCKET
              value: {{ .Values.global.s3.bucketPrefix }}eo-logs
            - name: BUCKET_NAME
              value: {{ .Values.global.s3.bucketPrefix }}eo-logs
            - name: EO_INIT_SVC_URL
              value: http://hzp-eo-initialization-svc.{{ .Release.Namespace }}.svc.cluster.local
            - name: ENABLE_INSTRUMENTATION
              value: {{ .Values.global.instrumentation.enabled | quote }}
            - name: DAP_BUCKET_NAME
              value: {{ .Values.global.s3.bucketPrefix }}dapo-logs
            - name: IS_DAP_OVA
              value: {{ .Values.global.ova.enabled | quote }}
            {{- if .Values.global.s3.credentials }}{{- toYaml .Values.global.s3.credentials | nindent 12 }}{{ end }}
            {{- toYaml $svc.env | nindent 12 }}
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: {{ $svc.port }}
          readinessProbe:
            httpGet:
              path: /admin/health/dependency
              port: {{ .Values.svc.port }}
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /admin/health/liveness
              port: {{ .Values.svc.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          startupProbe:
            httpGet:
              path: /admin/health/liveness
              port: {{ .Values.svc.port }}
            failureThreshold: 30
            periodSeconds: 3
          volumeMounts:
            - name: hzp-shared-pvc
              mountPath: /data
            {{- include "logLevel.configMap.mount" $ | indent 12 }}
      volumes:
        - name: ese-config
          configMap:
            name: hzp-product-config
        - name: machine-id
          configMap:
            name: hzp-product-config
        - name: ese-pvc
          {{- if .Values.ese.pvc.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.ese.pvc.name }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: hzp-shared-pvc
          {{- if .Values.ese.pvc.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.shared.pvc.name }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- include "logLevel.configMap.volume" $ | indent 8 }}
