apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.svc.name }}
spec:
  type: {{ .Values.svc.service.type }}
  ports:
    - port: {{ .Values.svc.service.port }}
      targetPort: {{ .Values.svc.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/app: {{ .Values.svc.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.svc.name }}
  labels:
    app.kubernetes.io/app: {{ .Values.svc.name }}
spec:
{{- if not .Values.svc.autoScaling.enabled }}
  replicas: {{ .Values.svc.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/app: {{ .Values.svc.name }}
  template:
    metadata:
      name: {{ .Values.svc.name }}
      labels:
        app.kubernetes.io/app: {{ .Values.svc.name }}
{{- tpl (toYaml .Values.svc.podLabels) . | replace "'" "" | nindent 8 }}
      annotations:
{{- tpl (toYaml .Values.svc.podAnnotations) . | replace "'" "" | nindent 8 }}
{{- if .Values.global.instrumentation.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.svc.port }}"
{{- end }}        
    spec:
      serviceAccountName: {{ if .Values.global.s3.serviceAccountAnnotations }}{{ .Values.svc.name }}{{ end }}
      {{- include "images.pullSecrets" . | nindent 6 }}
      securityContext:
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.svc $ )| trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.svc $ ) | trim | nindent 8 }}
      affinity: {{- include "pods.affinity" ( list .Values.svc $ ) | trim | nindent 8 }}
      containers:
        - image: {{ include "manifest.image.name" (dict "data" (index .Values.components .Values.svc.image.name ) "repo" .Values.global.repository) }}
          name: {{ .Values.svc.name }}
          {{ $_ := set .Values "iamProxyEntry" "./main" }}
          {{ tpl (toYaml .Values.global.iamProxy.commandDecorator) . | nindent 10 }}
          imagePullPolicy: {{ .Values.svc.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.svc.port }}
          resources:
            {{- toYaml .Values.svc.resources | nindent 12 }}
          env:
            - name: SIDECAR_INJECTED
              value: "{{ .Values.global.iamProxy.sidecarEnabled }}"
            - name: S3_URL
              value: {{ tpl .Values.global.s3.url . | quote }}
            - name: S3_REGION
              value: {{ .Values.global.s3.region | default "us-east-1" }}
            - name: S3_BUCKET
              value: {{ .Values.global.s3.bucketPrefix }}repository
            - name: NATS_URL
              value: "nats://jetstream.{{ .Release.Namespace }}.svc.cluster.local:4222"
            - name: JOB_SVC_BASE_URL
              value: "http://hzp-job-svc.{{ .Release.Namespace }}.svc.cluster.local"
            - name: ENABLE_INSTRUMENTATION
              value: {{ .Values.global.instrumentation.enabled | quote }}
            - name: EO_IP
              value: {{ .Values.global.ingress.fqdn }}
            - name: EO_NAME
              value: {{ .Values.global.eoName }}
            - name: UPGRADE_SVC_BASE_URL
              value: "http://hzp-upgrade-svc.{{ .Release.Namespace }}.svc.cluster.local"
            - name: SCHEDULER_SVC_BASE_URL
              value: "http://hzp-scheduler-svc.{{ .Release.Namespace }}.svc.cluster.local"
            - name: VAULT_HOST
              value: "http://edgevault.{{ .Release.Namespace }}.svc.cluster.local"
            - name: VAULT_PORT
              value: "8200"
            {{- if .Values.global.catalog.auth.dellDigitalAppID }}
            - name: DELL_DIGITAL_L7_APP_ID
              value: {{ .Values.global.catalog.auth.dellDigitalAppID }}
            {{- end }}
            {{- if .Values.global.catalog.auth.dellDigitalAppName }}
            - name: DELL_DIGITAL_L7_APP_NAME
              value: {{ .Values.global.catalog.auth.dellDigitalAppName }}
            {{- end }}
            {{- if .Values.global.catalog.auth.dellDigitalURL }}
            - name: DELL_DIGITAL_L7_URL
              value: {{ .Values.global.catalog.auth.dellDigitalURL }}
            {{- end }}
            {{- if .Values.global.catalog.auth.dellDigitalTokenURL }}
            - name: DELL_DIGITAL_TOKEN_URL
              value: {{ .Values.global.catalog.auth.dellDigitalTokenURL }}
            {{- end }}
            {{- if .Values.global.catalog.auth.dellDigitalClientID }}
            - name: DELL_DIGITAL_CLIENT_ID
              value: {{ .Values.global.catalog.auth.dellDigitalClientID }}
            {{- end }}
            {{- if .Values.global.catalog.auth.dellDigitalClientSecret }}
            - name: DELL_DIGITAL_CLIENT_SECRET
              value: {{ .Values.global.catalog.auth.dellDigitalClientSecret }}
            {{- end }}
            - name: PLUGINS_BP_PUBLIC_CATALOG_BRAND
              value: {{ include "plugins.bp.brand" (dict "dsp" .Values.global.dsp.enabled "brand" .Values.public_catalog.brand) }}
            - name: DELL_DIGITAL_DEPLOY_MODE
              value: {{ .Values.global.catalog.auth.dellDigitalMode }}
            - name: PUBLIC_CATALOG_ENABLED
              value: {{ .Values.global.catalog.public.enabled | quote }}
            {{ if  (index .Values.global "is-saas-env") }}
            - name: PORTAL_BASE_URL
              value: {{ .Values.global.dsp.portal.url }}
            - name: IS_SAAS_ENV
              value: "true"
            {{- else }}
            - name: PORTAL_BASE_URL
              value: {{ .Values.global.catalog.public.portal.baseURL }}
            - name: IS_SAAS_ENV
              value: "false"
            {{- end }}
            - name: FUSION_SVC_URL
              value: "http://fusion-entrypoint.{{ .Release.Namespace }}.svc.cluster.local"
            - name: PORTAL_CLIENT_KEY
              value: "portal-client-credentials"
            {{- if .Values.global.s3.credentials }}{{- toYaml .Values.global.s3.credentials | nindent 12 }}{{ end }}
            {{- toYaml .Values.svc.env | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: catalog-init-volume
              mountPath: "/app/config/"
              readOnly: true
            {{- include "logLevel.configMap.mount" $ | indent 12 }}
      volumes:
        - name: catalog-init-volume
          configMap:
            name: catalog-init-config
        {{- include "logLevel.configMap.volume" $ | indent 8 }}
      initContainers:
      - name: init-postgres
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
          allowPrivilegeEscalation: false
        env:
          - name: waiting_for_postgres_to_be_initialized
            valueFrom:
              configMapKeyRef:
                key: waiting_for_postgres_to_be_initialized
                name: infra-status-config
          {{- toYaml .Values.svc.env | nindent 10 }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for PostgreSQL to become ready...'
            until printf "." && nc -z -w 2 $DB_HOST $DB_PORT; do
                sleep 2;
            done;
            echo 'PostgreSQL OK ✓'
      - name: init-vault
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
          allowPrivilegeEscalation: false
        command:
          - sh
          - -c
          - |
            echo 'Waiting for Vault to become ready...'
            until printf "." && nc -z -w 2 edgevault 8200; do
              sleep 2;
            done;
            echo 'Vault OK ✓'
      - name: init-scheduler
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
          allowPrivilegeEscalation: false
        command:
          - sh
          - -c
          - |
            echo 'Waiting for scheduler-svc to become ready...'
            until printf "." && nc -z -w 2 hzp-scheduler-svc 80; do
                sleep 2;
            done;
            echo 'scheduler-svc OK ✓'
      {{- if .Values.global.seaweedfs.enabled }}
      - name: init-seaweedfs-s3
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
          allowPrivilegeEscalation: false
        command:
          - sh
          - -c
          - |
            echo 'Waiting for Seaweedfs S3 to become ready...'
            until [ "$response" = "200" ]; do
              response=$(wget -S -O /dev/null {{ tpl .Values.global.s3.url . }}/status 2>&1 | awk '/HTTP\/1.1/ {print $2}')
              printf "." && sleep 2
            done
            echo 'Seaweedfs S3 OK ✓'
      {{- end }}
