annotations:
  containerImages: |
    - compute-svc
    - busybox
    - compute-smoke-test
apiVersion: v2
appVersion: latest
description: A Helm chart for compute-svc, which manages the deployment status of
  VM and container
name: hzp-compute-svc
type: application
version: 0.1.0
