apiVersion: v1
kind: Service
metadata:
  name: {{ template "fusion-services.name" . }}-api-service
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.api_service.port }}
  selector:
    app: api-service
  type: ClusterIP
