{{- if .Values.deployments.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fusion-services.name" . }}-deployments-config
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.deployments.config | toYaml | nindent 4 }}
{{- end }}
