annotations:
  buildWorkflowURL: https://github.com/fusion-e/dsp-portal-gui/actions/runs/15755039899/attempts/1
apiVersion: v2
appVersion: 0.0.145
description: dell Deployment Helm Chart
name: dsp-portal-gui-chart
type: application
version: 0.0.145
