annotations:
  buildWorkflowURL: https://github.com/fusion-e/dsp-ingress-authz-svc/actions/runs/15754437800/attempts/1
  imagetag: latest
apiVersion: v2
appVersion: 0.0.16
dependencies:
- condition: global.installDependencies
  name: dsp-portal-nats-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com
  version: 0.1.8
description: A Helm chart for dsp-ingress-authz-svc, a service to integrate Vault
  to Istio Ingress
name: dsp-ingress-authz-svc-chart
type: application
version: 0.0.16
