apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fusion-services.name" . }}-rest-service-config
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
data:
  config.yaml: |
    {{ tpl (.Values.rest_service.config | toYaml | nindent 4) . }}
