{{- if and (not .Values.seaweedfs.enabled) (not .Values.rest_service.irsa_service_account) (.Values.rest_service.s3_access.aws_access_key_id) (.Values.rest_service.s3_access.aws_secret_access_key) }}
{{- $hook_annotations := dict "helm.sh/hook" "pre-install,pre-upgrade" "helm.sh/hook-delete-policy" "before-hook-creation" }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ .Values.rest_service.s3_access.k8s_secret_name }}
  labels:
    app: {{ template "fusion-services.name" . }}
    chart: {{ template "fusion-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations $hook_annotations ) | nindent 4 }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.rest_service.s3_access.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.rest_service.s3_access.aws_secret_access_key }}
{{- if .Values.rest_service.s3_access.aws_session_token }}
  AWS_SESSION_TOKEN: {{ .Values.rest_service.s3_access.aws_session_token }}
{{- end }}
{{- end }}
