apiVersion: v1
data:
     realm.json: {{ include "dell_realm_json" . | toString | b64enc | quote }}
     internal-realm.json: {{ include "internal_realm_json" . | toString | b64enc | quote }}
kind: Secret
metadata:
  name: realm-secret
  namespace: {{ .Release.Namespace }}
