annotations:
  buildWorkflowURL: https://github.com/fusion-e/dsp-secrets-service/actions/runs/15332579105/attempts/1
apiVersion: v2
appVersion: 0.0.12
dependencies:
- condition: global.installDependencies
  name: postgresql-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com/bitnami
  version: 16.5.3-official
- condition: global.standAloneDeploy
  name: dsp-portal-vault-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com
  version: 0.9.3
- alias: dbinit
  condition: dbinit.postgres.enabled
  name: dsp-portal-db-init-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com
  version: 0.0.16
- condition: global.installDependencies
  name: dsp-portal-nats-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com
  version: 0.1.8
description: dell Deployment Helm Chart
name: dsp-secrets-service-chart
type: application
version: 0.0.12
