apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fusion-services.name" . }}-nginx-master-config
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "nginx-configs/nginx.conf" | indent 4 }}
