apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.entrypoint.name }}
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.nginx.http_port }}
  selector:
    fusion-name: nginx
  type: ClusterIP
