apiVersion: v1
kind: Secret
metadata:
    name: {{ include "microservice.fullname" . }}
    namespace: {{ include "microservice.namespace" . | quote }}
    labels:
      hzp-app: "portal-infra"
      hzp-role: "dapp"
type: Opaque
data:
  {{- if .Values.vms.enabled }}
  VMS_ACCESS_TOKEN_ENDPT: {{ .Values.vms.vmsAccessTokenEndpoint | b64enc | quote }}
  VMS_ACCESS_TOKEN_TYPE: {{ .Values.vms.vmsAccessTokenType | b64enc | quote }}
  VMS_XFER_VOUCHER_ENDPT: {{ .Values.vms.vmsXferVoucherEndpoint | b64enc | quote }}
  VMS_XFER_VOUCHER_TYPE: {{ .Values.vms.vmsXferVoucherType | b64enc | quote }}
  VMS_XFER_VOUCHER_OAUTH: {{ .Values.vms.vmsXferVoucherOAuth | b64enc | quote }}
  VMS_XFER_VOUCHER_APP_ID: {{ .Values.vms.vmsXferVoucherAppId | b64enc | quote }}
  VMS_XFER_VOUCHER_SECRET: {{ .Values.vms.vmsXferVoucherSecret | b64enc | quote }}
  {{- end }}
