# This is a secret used to populate ENCRYPTION_KEY environment variable in
# `rest-service` and `mgmtworker` deployments. It has to be double base64
# encoded: first b64enc is for Kubernetes, the second for fusion manager.
{{- $prefix := include "microservice.fullname" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s%s" $prefix "-manager-security") }}
{{- $existingSecretOldName := lookup "v1" "Secret" .Release.Namespace "manager-security" }}
{{- $hook_annotations := dict "helm.sh/hook" "pre-install,pre-upgrade" "helm.sh/hook-delete-policy" "before-hook-creation" }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ $prefix }}-manager-security
  labels:
    app: {{ template "microservice.fullname" . }}
    chart: {{ template "microservice.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml $hook_annotations | nindent 4 }}
data:
{{- if $existingSecret }}
{{ toYaml $existingSecret.data | trim | nindent 2 }}
{{- else if $existingSecretOldName }}
{{ toYaml $existingSecretOldName.data | trim | nindent 2 }}
{{- else }}
  encryptionKey: {{ ( randAlphaNum 64 ) | b64enc | b64enc }}
  secretKey: {{ ( randAlphaNum 64 ) | b64enc }}
  hashSalt: {{ ( randAlphaNum 64 ) | b64enc }}
{{- end }}
