{{- if and .Values.global.iamAuthZEnabled false }}
{{ $svc := .Values.webhookSvc }}
{{- $ca := genCA $svc.name 36500 -}}
{{- $dns1 := $svc.name -}}
{{- $dns2 := printf "%s.%s" $svc.name .Release.Namespace -}}
{{- $dns3 := printf "%s.%s" $dns2 "svc" -}}
{{- $dns4 := printf "%s.%s" $dns3 "cluster.local" -}}
{{- $signed := genSignedCert $svc.name nil (list $dns1 $dns2 $dns3 $dns4) 36500 $ca -}}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ $svc.configName }}"
  labels:
    app: {{ $svc.configName }}
    env: "{{ .Release.Namespace }}"F
    name: "{{ $svc.configName }}"
    globalName: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ $svc.configName }}"
  annotations:
    "helm.sh/hook": pre-install
webhooks:
  - name: {{ printf "%s.%s.%s" $svc.name "injector" .Release.Namespace  }}
    clientConfig:
      caBundle: {{ $ca.Cert | b64enc }}
      service:
        name: {{ $svc.name }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: 443
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
        scope: "Namespaced"
    sideEffects: None
    timeoutSeconds: 5
    reinvocationPolicy: Never
    failurePolicy: Fail
    objectSelector:
      matchExpressions:
        - operator: In
          key: hzp.iam.webhook/active
          values:
            - "true"
    namespaceSelector:
      matchExpressions:
        - key: hzp.iam.webhook/active
          operator: In
          values:
            - "true"
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - {{ .Release.Namespace }}
    admissionReviewVersions:
      - v1
      - v1beta1
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svc.name }}
  annotations:
    "helm.sh/hook": pre-install
data:
  key.crt: {{ $signed.Key | b64enc }}
  ca.crt: {{ $signed.Cert | b64enc }}

{{end}}
