{{- $svc := .Values.svc -}}
{{- if or (.Values.global.regressionEnabled) (.Values.global.dataCollectionSvc.smoketestEnabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: datacollection-smoke-test
spec:
  template:
    metadata:
      name: datacollection-smoke-test
      labels:
{{- tpl (toYaml .Values.test.podLabels) . | replace "'" "" | nindent 8 }}
    spec:
      {{- include "images.pullSecrets" . | nindent 6 }}
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.svc $ )| trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.svc $ ) | trim | nindent 8 }}
      affinity: {{- include "pods.affinity" ( list .Values.svc $ ) | trim | nindent 8 }}
      containers:
      - name: datacollection-smoke-test-container
        env:
          - name: AWS_URL
            value: {{ tpl .Values.global.s3.url . | quote }}
          - name: AWS_REGION
            value: {{ .Values.global.s3.region | default "us-east-1" }}
          - name: HTTP_LOGS_URL
            value: "http://fluentbit.{{ .Release.Namespace }}.svc.cluster.local"
          - name: BASE_URL
            value: "http://{{ .Values.test.service.fullname }}.{{ .Release.Namespace }}.svc.cluster.local"
          {{- toYaml .Values.test.env | nindent 10 }}
          - name: RP_ENDPOINT
            value: "{{ .Values.test.reportportal.rpendpoint }}"
          - name: RP_API_KEY
            value: "{{ .Values.test.reportportal.rpuuid }}"
          - name: RP_MODE
            value: default
          - name: RP_PROJECT
            value: HZP_EO_SERVICES
          - name: RP_LAUNCH
            value: "{{ .Values.test.service.fullname }}"
          - name: RP_ATTRIBUTES
            value: "RELEASE_VERSION:{{ .Values.test.reportportal.release }};EO_IP:{{ .Values.test.reportportal.eourl }};EO_MANIFEST:{{ .Values.test.reportportal.manifest }};TEST_GROUP:{{ .Values.test.reportportal.suite }};RP_LAUNCH_KEY_ATTRIBUTE:{{ .Values.test.reportportal.runid }};;RELEASE_VERSION:{{ .Values.test.reportportal.release }};"
            {{- if .Values.global.s3.credentials }}{{- toYaml .Values.global.s3.credentials | nindent 10 }}{{ end }}
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components .Values.test.image.name ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command: ['/bin/sh', '-c']
        # Sleep before test to allow netpol and istio-proxy to take effect
        # Sleep after the test is to enable pipeline to copy the test result when pod is running state
        args:
          - |
            sleep 60; echo All dependent components are running. Start testing!;
            java -jar tests.jar {{ .Values.test.testsuite }}; sleep 120;
            if wget -q --post-data='' -S -O /dev/null http://127.0.0.1:15020/quitquitquit 2>/dev/null; then
                echo "Terminated istio-proxy."
            fi
      initContainers:
      - name: init-postgres
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for PostgreSQL to become ready...'

            until printf "." && nc -z -w 2 {{ .Values.test.postgresql.service.fullname }} {{ .Values.test.postgresql.service.port }}; do
                sleep 2;
            done;

            echo 'PostgreSQL OK ✓' 
      - name: init-datacollection-svc
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for datacollection service to become ready...'

            until printf "." && nc -z -w 2 {{ .Values.test.service.fullname }} {{ .Values.test.service.port }}; do
                sleep 2;
            done;

            echo 'Hzp-datacollection-svc OK ✓'
      serviceAccountName: {{ .Values.test.rbac.namePrefix }}-sa
      restartPolicy: Never

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.test.rbac.namePrefix }}-sa
  {{- if .Values.global.s3.serviceAccountAnnotations }}
  annotations:
    {{- .Values.global.s3.serviceAccountAnnotations | toYaml | nindent 4 }}
  {{- end }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ .Values.test.rbac.namePrefix }}-role"
  labels:
    env: "{{ .Release.Namespace }}"
    name: "{{ .Values.test.rbac.namePrefix }}-role"
    globalName: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ .Values.test.rbac.namePrefix }}-role"
rules:
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "*" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ .Values.test.rbac.namePrefix }}-rolebinding"
  labels:
    env: "{{ .Release.Namespace }}"
    name: "{{ .Values.test.rbac.namePrefix }}-rolebinding"
    globalName: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ .Values.test.rbac.namePrefix }}-rolebinding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ .Values.test.rbac.namePrefix }}-role"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.test.rbac.namePrefix }}-sa
    namespace: {{ .Release.Namespace }}

{{- end }}
