annotations:
  buildWorkflowURL: https://github.com/fusion-e/dsp-catalog-svc/actions/runs/15754665719/attempts/1
apiVersion: v2
appVersion: 0.0.197
dependencies:
- condition: global.installDependencies
  name: postgresql-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com/bitnami
  version: 16.5.3-official
- alias: dbinit
  condition: dbinit.postgres.enabled
  name: dsp-portal-db-init-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com
  version: 0.0.16
- condition: global.installDependencies
  name: dsp-portal-nats-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com
  version: 0.1.8
description: DSP Portal Catalog Helm Chart
name: dsp-catalog-svc-chart
type: application
version: 0.0.197
