{{- $name := include "fusion-services.name" . -}}
{{- if .Values.db.k8sSecret.create }}
{{- $db_creds_secret := (lookup "v1" "Secret" .Release.Namespace .Values.db.k8sSecret.name ) }}
{{- if or (not $db_creds_secret) (and $db_creds_secret (eq (index $db_creds_secret.metadata.annotations "meta.helm.sh/release-name") .Release.Name) (eq $db_creds_secret.metadata.labels.app $name)) }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ .Values.db.k8sSecret.name }}
  labels:
    app: {{ template "fusion-services.name" . }}
    chart: {{ template "fusion-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
{{- if $db_creds_secret }}
data:
  {{ .Values.db.k8sSecret.key }}: {{ get $db_creds_secret.data .Values.db.k8sSecret.key }}
{{- else }}
stringData:
  {{- if .Values.db.password }}
  {{ .Values.db.k8sSecret.key }}: {{ .Values.db.password }}
  {{- else }}
  {{ .Values.db.k8sSecret.key }}: {{ randAlphaNum 16 }}
  {{- end}}
{{- end }}
{{- end }}
{{- end }}
