# This is a secret used to populate FUSION_AUTH_PSK environment variable in
# `rest-service` and `blueprint` deployments
{{- $prefix := include "fusion-services.name" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s%s" $prefix "-auth-signing") }}
{{- $existingSecretOldName := lookup "v1" "Secret" .Release.Namespace "fusion-auth-signing" }}
{{- $hook_annotations := dict "helm.sh/hook" "pre-install,pre-upgrade" "helm.sh/hook-delete-policy" "before-hook-creation" }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ template "fusion-services.name" . }}-auth-signing
  labels:
    app: {{ template "fusion-services.name" . }}
    chart: {{ template "fusion-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations $hook_annotations ) | nindent 4 }}
data:
  {{- if $existingSecret }}
{{ toYaml $existingSecret.data | trim | indent 2 }}
  {{- else if $existingSecretOldName }}
{{ toYaml $existingSecretOldName.data | trim | indent 2 }}
  {{- else }}
  psk: {{ ( randAlphaNum 64 ) | b64enc }}
  {{- end }}
