{{- $certs := include "fusion-services.gen-certs" . -}}
{{- $prefix := include "fusion-services.name" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s%s" $prefix "-ssl-certs") }}
{{- $existingSecretOldName := lookup "v1" "Secret" .Release.Namespace "ssl-certs" }}
{{- $hook_annotations := dict "helm.sh/hook" "pre-install,pre-upgrade" "helm.sh/hook-delete-policy" "before-hook-creation" }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: {{ $prefix }}-ssl-certs
  labels:
    app: {{ template "fusion-services.name" . }}
    chart: {{ template "fusion-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations $hook_annotations ) | nindent 4 }}
data:
  {{- if $existingSecret }}
{{ toYaml $existingSecret.data | trim | indent 2 }}
  {{- else if $existingSecretOldName }}
{{ toYaml $existingSecretOldName.data | trim | indent 2 }}
  {{- else }}
    {{- $certs | indent 2 }}
  {{- end }}

{{- /* For bitnami/rabbitmq subchart (secret keys hardcoded)
       Should be in the same template file with main certs for avoid generating separate certs */ -}}
{{- if .Values.rabbitmq.enabled }}
{{- $existingSecretRabbit := lookup "v1" "Secret" .Release.Namespace "rabbitmq-ssl-certs" }}
---
apiVersion: v1
kind: Secret
type: opaque
metadata:
  name: rabbitmq-ssl-certs
  labels:
    app: {{ template "fusion-services.name" . }}
    chart: {{ template "fusion-services.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations $hook_annotations ) | nindent 4 }}
data:
  {{- if $existingSecretRabbit }}
{{ toYaml $existingSecretRabbit.data | trim | indent 2 }}
  {{- else }}
    {{- regexReplaceAll "cloudify_.*" ( regexReplaceAll "rabbitmq-key.pem" ( regexReplaceAll "rabbitmq-cert.pem" ( regexReplaceAll "cloudify_internal_ca_cert.pem" $certs "ca.crt" ) "tls.crt" ) "tls.key" ) "" | indent 2 }}
  {{- end }}
{{- end }}
