annotations:
  buildWorkflowURL: https://github.com/fusion-e/dsp-iam-policy-svc/actions/runs/15705794133/attempts/1
apiVersion: v2
appVersion: 0.0.40
dependencies:
- condition: global.installDependencies
  name: postgresql-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com/bitnami
  version: 16.5.3-official
- alias: dbinit
  condition: dbinit.postgres.enabled
  name: dsp-portal-db-init-chart
  repository: oci://702886132326.dkr.ecr.eu-west-1.amazonaws.com
  version: 0.0.16
description: dell Deployment Helm Chart
name: dsp-iam-policy-svc-chart
type: application
version: 0.0.40
