{{- $svc := .Values.svc -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc.name }}
  labels:
    hzp-app: {{ $svc.name }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      hzp-app: {{ $svc.name }}
  template:
    metadata:
      labels:
{{- tpl (toYaml .Values.svc.podLabels) . | replace "'" "" | nindent 8 }}
      annotations:
        hzp.iam.webhook/resources-limits-memory: "2000Mi"
        hzp.iam.webhook/authentication-enabled: "false"
        hzp.iam.webhook/authorization-enabled: "false"
    spec:
      {{- include "images.pullSecrets" . | nindent 6 }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.svc $ ) | trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.svc $ ) | trim | nindent 8 }}
      affinity: {{- include "pods.affinity" ( list .Values.svc $ ) | trim | nindent 8 }}
      containers:
        - image: {{ include "manifest.image.name" (dict "data" (index .Values.components .Values.svc.image.name ) "repo" .Values.global.repository) }}
          imagePullPolicy: "Always"
          name: {{ $svc.name }}
          ports:
            - containerPort: {{ $svc.port }}
          resources:
            {{- toYaml .Values.svc.resources | nindent 12 }}
          env:
            - name: SERVICE_VERSION
              value: "{{ uuidv4 }}"
            {{- toYaml $svc.env | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
            allowPrivilegeEscalation: false
          volumeMounts:
            {{- include "logLevel.configMap.mount" $ | indent 12 }}
      initContainers:
        - name: dbchecker
          image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
          imagePullPolicy: {{ .Values.dbchecker.image.pullPolicy }}
          securityContext:
        {{- toYaml .Values.dbchecker.securityContext | nindent 12 }}
          env: 
            {{- toYaml $svc.env | nindent 12 }}
          command:
            - sh
            - -c
            - |
              echo 'Waiting for PostgreSQL to become ready...'

              until printf "." && nc -z -w 2 $DB_HOST $DB_PORT; do
                  sleep 2;
              done;

              echo 'PostgreSQL OK ✓'
      volumes:
        {{- include "logLevel.configMap.volume" $ | indent 8 }}
