annotations:
  buildWorkflowURL: https://github.com/fusion-e/dsp-services-gui/actions/runs/15701029869/attempts/1
apiVersion: v2
appVersion: 0.0.56
description: dell Deployment Helm Chart
name: dsp-services-gui-chart
type: application
version: 0.0.56
