apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gw-conf-includes-internal
  namespace: {{ .Release.Namespace | quote }}
  annotations:
data:
{{ (tpl (.Files.Glob "files/internal/*.template").AsConfig .) | indent 2 }}