apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-gw-maintenance-config
  namespace: {{ .Release.Namespace | quote }}
  annotations:
data:
  maintenanceMode: {{ .Values.maintenanceMode | quote }}
