{{- if and (.Values.autoScaling.enabled) (or (eq "eks" $.Values.global.k8s.distro) (not $.Values.global.temp.portalTransition.enableLoadBalancer)) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-gw
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: nginx-gw
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-gw
  minReplicas: {{ .Values.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.autoScaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.autoScaling.metrics | nindent 4 }}
  behavior:
    {{- toYaml .Values.autoScaling.behavior | nindent 4 }}
{{- end }}
