apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: nginx-gw
  name: nginx-gw
  namespace: {{ .Release.Namespace | quote }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: nginx-gw

