{{- $secretName := "fqdn-history-secret" }}
{{- $namespace := .Release.Namespace }}

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $namespace }}
  name: {{ $secretName }}
data:
  history: {{- include "GetFqdnHistoryList" (dict "namespace" $namespace "fqdn" $.Values.global.ingress.fqdn) | b64enc | indent 1 }}
