apiVersion: v1
kind: Service
metadata:
  name: nginx-gw
  namespace: {{ .Release.Namespace | quote }}
  annotations:
   {{- with .Values.tlsService.annotations }}
     {{- toYaml . | nindent 4 }}
   {{- end }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: nginx-80-80
    - protocol: TCP
      port: 443
      targetPort: 443
      name: nginx-443-443
  selector:
    app: nginx-gw
  type: {{ .Values.tlsService.type }}
{{- if $.Values.global.temp.portalTransition.enableLoadBalancer }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gw-mtls
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- if .Values.mtlsService.annotations }}
     {{- with .Values.mtlsService.annotations }}
       {{- toYaml . | nindent 4 }}
     {{- end }}
   {{- else }}
     {{- with .Values.global.istio.ingressgateway.annotations }}
       {{- toYaml . | nindent 4 }}
     {{- end }}
   {{- end }}
  labels:
    app: nginx-gw
    hzp-app: nginx-gw
spec:
  type: {{ default (((.Values.global).istio).ingressgateway).type .Values.mtlsService.type }}
  allocateLoadBalancerNodePorts: {{ .Values.mtlsService.allocateLoadBalancerNodePorts }}
  selector:
    app: nginx-gw
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  externalTrafficPolicy: Local
{{- end }}

{{- if .Values.global.oob.oobEnabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gw-oob
  namespace: {{ .Release.Namespace | quote }}
  annotations:
  {{- if .Values.mtlsService.annotations }}
     {{- with .Values.mtlsService.annotations }}
       {{- toYaml . | nindent 4 }}
     {{- end }}
   {{- else }}
     {{- with .Values.global.istio.ingressgateway.annotations }}
       {{- toYaml . | nindent 4 }}
     {{- end }}
   {{- end }}
  labels:
    app: nginx-gw
    hzp-app: nginx-gw
spec:
  type: {{ default (((.Values.global).istio).ingressgateway).type .Values.mtlsService.type }}
  allocateLoadBalancerNodePorts: {{ .Values.mtlsService.allocateLoadBalancerNodePorts }}
  selector:
    app: nginx-gw
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.global.oob.oobLoadBalancerIP }}
{{- end }}
