{{- $namespace := .Release.Namespace }}
# TLS ca, cert and key
{{- $tlsCA := genCAWithKey "hzp.eo" 365 (genPrivateKey "ecdsa") -}}
{{- $tlsSAN := list "default.dell.com" }}
{{- range $.Values.tlsHost }}
  {{- $tlsSAN = append $tlsSAN . }}
{{- end }}
{{- range $.Values.tlsHostFidoRV }}
  {{- $tlsSAN = append $tlsSAN . }}
{{- end }}
{{- $tlsCert := genSignedCertWithKey "dell.com" nil $tlsSAN 365 $tlsCA (genPrivateKey "ecdsa") -}}

# mTLS ca, cert and key
{{- $mTLSCA := genCAWithKey "hzp.eo" 365 (genPrivateKey "ecdsa") -}}
{{- $mTLSSAN := list "" }}
{{- $updatedmTLSHostList := include "GetMTLSHostList" (dict "namespace" $namespace "fqdn" $.Values.global.ingress.fqdn "prefix" $.Values.global.istio.defaultPrefix.mTLSHost "default" $.Values.global.istio.mTLSHost) }}
{{- range $index, $element := (splitList "," $updatedmTLSHostList) -}}
  {{- $mTLSSAN = append $mTLSSAN . }}
{{- end }}
{{- $updatedmTLSRecoveryHostList := include "GetMTLSHostList" (dict "namespace" $namespace "fqdn" $.Values.global.ingress.fqdn "prefix" $.Values.global.istio.defaultPrefix.mTLSHostRecovery "default" $.Values.global.istio.mTLSHostRecovery) }}
{{- range $index, $element := (splitList "," $updatedmTLSRecoveryHostList) -}}
  {{- $mTLSSAN = append $mTLSSAN . }}
{{- end }}
{{- $mTLSCert := genSignedCertWithKey "dell.com" nil $mTLSSAN 365 $mTLSCA (genPrivateKey "ecdsa") -}}

# Recovery cert and key
{{- $recoveryCA := genCAWithKey "hzp.eo" 365 (genPrivateKey "ecdsa") -}}
{{- $recoverySAN := list "" }}
{{- $updatedmTLSRecoveryHostList := include "GetMTLSHostList" (dict "namespace" $namespace "fqdn" $.Values.global.ingress.fqdn "prefix" $.Values.global.istio.defaultPrefix.mTLSHostRecovery "default" $.Values.global.istio.mTLSHostRecovery) }}
{{- range $index, $element := (splitList "," $updatedmTLSRecoveryHostList) -}}
  {{- $recoverySAN = append $recoverySAN . }}
{{- end }}
{{- $recoveryCert := genSignedCertWithKey "dell.com" nil $recoverySAN 365 $recoveryCA (genPrivateKey "ecdsa") -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-credential
  namespace: {{ .Release.Namespace | quote }}
data:
  cacert: {{ $tlsCA.Cert | b64enc }}
  cakey_default: {{ $tlsCA.Key | b64enc }} # Added for development
  cert: {{ $tlsCert.Cert | b64enc }}
  key: {{ $tlsCert.Key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mtls-credential
  namespace: {{ .Release.Namespace | quote }}
data:
  cacert: {{ $mTLSCA.Cert | b64enc }}
  cakey_default: {{ $mTLSCA.Key | b64enc }} # Added for development
  cert: {{ $mTLSCert.Cert | b64enc }}
  key: {{ $mTLSCert.Key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mtls-credential-recovery
  namespace: {{ .Release.Namespace | quote }}
data:
  cacert: {{ $recoveryCA.Cert | b64enc }}
  cakey_default: {{ $recoveryCA.Key | b64enc }} # Added for development
  cert: {{ $mTLSCert.Cert | b64enc }}
  key: {{ $mTLSCert.Key | b64enc }}
