apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.svc.rbac.namePrefix }}-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.svc.rbac.namePrefix }}-role
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    resourceNames: [ "tls-credential", "mtls-credential", "mtls-credential-recovery" ]
    verbs: [ "get","update","watch" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    resourceNames: [ "vault-bootstrap" ]
    verbs: [ "list","get","watch" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.svc.rbac.namePrefix }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.svc.rbac.namePrefix }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.svc.rbac.namePrefix }}-sa
    namespace: {{ .Release.Namespace }}
