apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-setup-configmap
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "postgresql.common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  hzp-setup.sh: |-
    #!/bin/bash
    set -o errexit
    set -o nounset
    set -o pipefail
    #set -o xtrace

    info "hzp setup custom environment"

    # Load Libraries
    . /opt/bitnami/scripts/postgresql-env.sh
    . /opt/bitnami/scripts/libpostgresql.sh
    . /opt/bitnami/scripts/liblog.sh

    postgresql_enable_nss_wrapper
    info "hzp setup begin" 

    #BITNAMI_DEBUG=false
    if ! is_postgresql_running; then

       error "hzp setup PostgreSQL is not running"
       exit 1

    else 
       export POSTGRESQL_USERNAME={{ .Values.global.postgresql.auth.hzpDbUserName | quote }}

       info "hzp setup user $POSTGRESQL_USERNAME"

       #local -r escaped_password="${POSTGRES_POSTGRES_PASSWORD//\'/\'\'}"

       #PGPASSWORD="$POSTGRES_POSTGRES_PASSWORD" /opt/bitnami/postgresql/bin/psql -U postgres -h 127.0.0.1 -c "CREATE ROLE $POSTGRESQL_USERNAME WITH LOGIN PASSWORD "\'$escaped_password\'";" -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $POSTGRESQL_USERNAME;" -c "ALTER USER $POSTGRESQL_USERNAME CREATEDB;"

       #info "hzp setup create db $POSTGRESQL_USERNAME"
       #postgresql_ensure_database_exists $POSTGRESQL_USERNAME -u $POSTGRESQL_USERNAME

       #info "hzp setup ensure user has_database_privileges $POSTGRESQL_USERNAME"
       #postgresql_ensure_user_has_database_privileges $POSTGRESQL_USERNAME $POSTGRESQL_USERNAME
    fi

    info "hzp setup completed ok"
