apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.svc.rbac.namePrefix }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.svc.rbac.namePrefix }}-hzp-role
rules:
  - apiGroups: [ "", "apps" ]
    resources: [ "configmaps", "pods" ]
    verbs: [ "get", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.svc.rbac.namePrefix }}-hzp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.svc.rbac.namePrefix }}-hzp-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.svc.rbac.namePrefix }}-sa
    namespace: {{ .Release.Namespace }}
