{{- $secretName := (printf "%s-opensearch-secret" (include "opensearch.fullname" .))}}
{{- $oldSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if or (not $oldSecret) (not $oldSecret.data) }}
{{- $secretName = (printf "mist-ee-opensearch-secret")}}
{{- $oldSecret = lookup "v1" "Secret" .Release.Namespace $secretName }}
{{ end}}
{{- $generatedRootPassword := (randAlphaNum 16) | lower -}}
{{- $generatedLogstashPassword := (randAlphaNum 16) | lower -}}
{{- $generatedReadOnlyPassword := (randAlphaNum 16) | lower -}}
{{- $userProvidedPassword := .Values.global.opensearch.password -}}
{{- $adminPassword := ternary $generatedRootPassword $userProvidedPassword .Values.global.opensearch.deploy -}}
{{- $logstashPassword := ternary $generatedLogstashPassword $userProvidedPassword .Values.global.opensearch.deploy -}}
{{- $readOnlyPassword := ternary $generatedReadOnlyPassword $userProvidedPassword .Values.global.opensearch.deploy -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opensearch.fullname" . }}-opensearch-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{- tpl (toYaml .Values.global.opensearch.statefulset.podLabels) . | replace "'" "" | nindent 8 }}
type: Opaque
stringData:
  {{- if or (not $oldSecret) (not $oldSecret.data) }}
  adminPassword: {{ $adminPassword }}
  logstashPassword: {{ $logstashPassword }}
  readOnlyPassword: {{ $readOnlyPassword }}
  {{- $ca := genCA "default-ca" 365 }}
  {{- $cert := genSignedCert "native.edge" nil nil 365 $ca }}
  node1.crt: {{ $cert.Cert | quote }}
  node1.key: {{ $cert.Key | quote }}
  ca.crt: {{ $ca.Cert | quote}}
  {{ else }}
  adminPassword: {{ index $oldSecret.data "adminPassword" | b64dec }}
  logstashPassword: {{ index $oldSecret.data "logstashPassword" | b64dec }}
  readOnlyPassword: {{ index $oldSecret.data "readOnlyPassword" | b64dec }}
  node1.crt: {{ index $oldSecret.data "node1.crt" | b64dec | quote }}
  node1.key: {{ index $oldSecret.data "node1.key" | b64dec | quote }}
  ca.crt: {{ index $oldSecret.data "ca.crt" | b64dec | quote }}
{{ end}}
