annotations:
  containerImages: |
    - hzp-event-display
    - busybox
apiVersion: v2
appVersion: latest
description: A Helm chart for hzp-event-display, a service that logs and persists
  all Events passed using Knative Eventing
name: hzp-event-display
type: application
version: 0.1.0
