apiVersion: v1
kind: Service
metadata:
  name: {{ template "fusion-services.name" . }}-stage-backend
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.stage_backend.port }}
  selector:
    app: stage-backend
  type: ClusterIP
