{{- template "vault.csiEnabled" . -}}
{{- if .csiEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ template "vault.fullname" . }}-csi-provider-clusterrolebinding"
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}-csi-provider
    app.kubernetes.io/instance: eo-management
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    env: "{{ .Release.Namespace }}"
    name: "{{ template "vault.fullname" . }}-csi-provider-clusterrolebinding"
    globalName: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ template "vault.fullname" . }}-csi-provider-clusterrolebinding"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ tpl .Values.global.clusterResourcesPrefix . }}{{ template "vault.fullname" . }}-csi-provider-clusterrole"
subjects:
- kind: ServiceAccount
  name: {{ template "vault.fullname" . }}-csi-provider
  namespace: {{ .Release.Namespace }}
{{- end }}
