annotations:
  containerImages: |
    - iam-webhook-svc
    - hzp-iam-proxy
    - hzp-iam-proxy-init
    - kubectl
apiVersion: v2
appVersion: latest
description: A Helm chart for the IAM proxy configurations
name: hzp-iam-webhooks
type: application
version: 0.1.0
