{{- if or (.Values.global.regressionEnabled) (.Values.global.rulesSvc.smoketestEnabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: rules-smoke-test
spec:
  template:
    metadata:
      name: rules-svc-smoke-test
      labels:
{{- tpl (toYaml .Values.test.podLabels) . | replace "'" "" | nindent 8 }}
    spec:
      {{- include "images.pullSecrets" . | nindent 6 }}
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.svc $ )| trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.svc $ ) | trim | nindent 8 }}
      affinity: {{- include "pods.affinity" ( list .Values.svc $ ) | trim | nindent 8 }}
      containers:
      - name: rules-svc-smoke-test-container
        env:
          - name: BASE_URL
            value: "http://{{ .Values.test.service.fullname }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: MESSAGING_URL
            value: "nats://jetstream.{{ .Release.Namespace }}.svc.cluster.local"
          - name: RP_ENDPOINT
            value: "{{ .Values.test.reportportal.rpendpoint }}"
          - name: RP_API_KEY
            value: "{{ .Values.test.reportportal.rpuuid }}"
          - name: RP_MODE
            value: default
          - name: RP_PROJECT
            value: HZP_EO_SERVICES
          - name: RP_LAUNCH
            value: "{{ .Values.test.service.fullname }}"
          - name: RP_ATTRIBUTES
            value: "RELEASE_VERSION:{{ .Values.test.reportportal.release }};EO_IP:{{ .Values.test.reportportal.eourl }};EO_MANIFEST:{{ .Values.test.reportportal.manifest }};TEST_GROUP:{{ .Values.test.reportportal.suite }};RP_LAUNCH_KEY_ATTRIBUTE:{{ .Values.test.reportportal.runid }};;RELEASE_VERSION:{{ .Values.test.reportportal.release }};"
          - name: TAGS_SVC_URL
            value: "http://hzp-tags-svc.{{ .Release.Namespace }}.svc.cluster.local"
          - name: ECE_SIMULATOR_URL
            value: "http://hzp-ece-simulator.{{ .Release.Namespace }}.svc.cluster.local/api/v1/simulated-ece"
          - name: SECRET_SERVER
            value: "http://fusion-entrypoint.{{ .Release.Namespace }}.svc.cluster.local/"
          - name: CERTIFICATE_SERVER
            value: "http://hzp-certificate-svc.{{ .Release.Namespace }}.svc.cluster.local/"
          {{- toYaml .Values.test.env | nindent 10 }}
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components .Values.test.image.name ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command: ['/bin/sh', '-c']
        #future enchancement: remove sleep before test, as of now dispatcher is taking time to connect to jetstream server
        ##sleep after the test is to enable pipeline to copy the test result when pod is running state
        args:
          - |
            echo All dependent components are running. Start testing!;
            java -jar tests.jar {{ .Values.test.testsuite }}; sleep 120;
            if wget -q --post-data='' -S -O /dev/null http://127.0.0.1:15020/quitquitquit 2>/dev/null; then
                echo "Terminated istio-proxy."
            fi
      initContainers:
      - name: init-postgres
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for Hzp Rule Service to become ready...'

            until printf "." && nc -z -w 2 {{ .Values.test.postgresql.service.fullname }} {{ .Values.test.postgresql.service.port }}; do
                sleep 2;
            done;

            echo 'PostgreSQL OK ✓' 
      - name: init-rules-svc
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for rules service to become ready...'

            until printf "." && nc -z -w 2 {{ .Values.test.service.fullname }} {{ .Values.test.service.port }}; do
                sleep 2;
            done;

            echo 'hzp-rules-svc OK ✓'
      restartPolicy: Never

{{- end }}
