global:
  registry: "702886132326.dkr.ecr.eu-west-1.amazonaws.com"
  installDependencies: true
  standAloneDeploy: true
  ingress:
    fqdn: ""
  postgres:
    internal: true
    host:
  
nameOverride: "dsp-portal-certificate-svc"
fullnameOverride: "dsp-portal-certificate-svc"

postgresql-chart:
  fullnameOverride: "postgresql"

replicaCount: 1

# values that contains list of tiems for configmap env:
extended_list_env:
extended_list_values:


#replace values from configmap.yaml of your service
#set the configs values Hardcoded from old vluefile env values.
# ALL!!! values must be in QUOTES!!!!
config:
  configmap:


# set all the deployment envs HERE!
# secretname= global.secretname
# keyToEnvName= the name of the env-ar on the pods (dell__Secret__ConnectionStrings__dellConnectionString)
# key = the actual key needed from the secret
# u can add more then 1 secret to use(see in your value global parameter)
externalsecrets:

extraEnvs:
  - name: NATS_URL
    value: nats:4222
  # NATS_MONITORING_URL used by init container
  - name: NATS_MONITORING_URL
    value: nats:8222
  - name: FUSION_SVC_INTERNAL_URL
    value: "http://dsp-secrets-service"
  - name: ENABLE_FUSION_SECRETS_CLIENT_MOCK
    value: "false"
  - name: EVENTING_TYPE
    value: "nats"
  - name: FQDN
    value: "{{ .Values.global.ingress.fqdn | default \"dsp-portal.dev.sp.dell.com\" }}"
  - name: TLS_CRED_NAMESPACE
    value: "{{ .Release.Namespace }}"
  - name: VAULT_HOST
    value: "http://edgevault"
  - name: VAULT_PORT
    value: "8200"
  - name: SESSION_SERVICE_URL
    value: "http://dsp-iam-session-svc"
  - name: ENABLE_INSTRUMENTATION
    value: "true"


image:
  image: "dsp-portal-certificate-svc"
  tag: ""
  pullPolicy: Always
  imagePullSecrets:
    - name: docker-secret

hzputil:
  image: "eo-images/hzp-util"
  tag: 0.1.3

busybox:
  image: "eo-images/busybox"
  tag: 1.36.1

# Postgres configuration
dbinit:
  postgres:
    enabled: true
    name: dsp-portal-certificate-svc
    dbName: "dsp_portal_certificate_svc" # The db username is the same as the db name by design

initjob:
  # for standalone chart, this job will not be successful, hence it is disabled
  # in portal chart, initjob.enabled of dsp-portal-certificate-svc-chart should be set to true
  enabled: false
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  resources:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      memory: "200Mi"
      cpu: 100m

dockerSecret:
  create: false
  dockerConfigJSON: ""

# set in deployment.yaml (previously was hardcoded inside the deployment)
entrypoint:
  cmd: dotnet
  arg: ""
  workingDir: "/home/dsp-portal-certificate-svc/"

containerPort:
  http: 8080

terminationGracePeriodSeconds: 30

lifecycle: {}

updateStrategy: {}

extraLabels: []

startupProbe:
  httpGet:
    path: /admin/health/liveness
    port: http
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /admin/health/liveness
    port: http
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /admin/health/liveness
    port: http
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

volumeMounts: {}
  # - name: nginx-conf
  #   mountPath: /etc/nginx/nginx.conf
  #   subPath: nginx.conf
  # - name: nginx-conf
  #   mountPath: /etc/nginx/security.conf
  #   subPath: security.conf
  # - name: nginx-conf
  #   mountPath: /etc/nginx/replacements.conf
  #   subPath: replacements.conf

deployment:
  enabled: true

# previus hardcoded in deployment.yaml
# now we can set dell.prod for pproduction apps (as for now all apps are dell.local)
# dnsConfig:
#   searches:

service:
  enabled: true
  type: ClusterIP
  labels: []
  http:
    port: 80
    targetPort: 8080
    nodePort: null
  #Only if you need one service to listen to two ports (Better to split that service to 2 mircoservices.)
  #Must be used with Multiple ingress paths.
  multiPortService:
    enabled: false
    http:
      port: 4999
      name: external
      targetPort: null

ingress:
  enabled: false
  #ALB Annotations: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#annotations
  annotations: {}
  hosts:
  - path: /
    pathType: ImplementationSpecific

  multipath:
    enabled: true
    hosts:
    - paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          # serviceName: app1-service
          servicePort: 8080
      - path: /health
        pathType: ImplementationSpecific
        backend:
          # serviceName: app1-service
          servicePort: 8080

# Whether or not we want a pod disruption budget, enabled by default, but this only is enabled if replicaCount > 1
podDistuptionBudget:
  enabled: true
  minAvailable: 1

resources:
  # same as orchestrator hzp-certificate-svc
  requests:
    memory: "25Mi"
    cpu: "5m"
  limits:
    memory: "200Mi"
    cpu: 100m


# we should use only HPA OR Keda.
# if keda is needed plz use keda as the cpu\mem scaler
autoscaling: # Only one can be enabled
  minReplicas: 1
  maxReplicas: 3
  hpa:
    enabled: true
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageValue: 150m
          type: Utilization
    - type: Resource
      resource:
        name: memory
        target:
          averageValue: 300Mi
          type: Utilization


# criticalinfra = all our criticalinfra apps (namespace criticalinfra)
# infrastructure = internal tools(like devtools apps)
# dell = rest of dell microservices (exclude criticalinfra)
# only 1 selector will be selected!!
nodeSelector: {}
  # kubernetes.io/os: linux


# The folowing property is mandetory only for critical infra!!!
# tolerations: {}
tolerations: {}
  # - key: "app"
  #   operator: "Equal"
  #   value: "dell"
  # - key: "app"
  #   operator: "Equal"
  #   value: "dell-prod"

volumes: {}
  # - name: nginx-conf
  #   configMap:
  #     name: nginx-conf
  #     items:
  #       - key: nginx.conf
  #         path: nginx.conf
  #       - key: security.conf
  #         path: security.conf
  #       - key: replacements.conf
  #         path: replacements.conf

podAntiAffinity:
  enabled: false

topologySpreadConstraints: {}



# Create serviceaccount for the service
serviceAccount:
  enabled: true
  annotations: {}
    # Here's an example of assigning an IAM role to a pod
    # eks.amazonaws.com/role-arn: arn:aws:iam::123123123:role/role-name-goes-here

#Commit: DEVOPS-5837-FR-Hashmaps
hashcalculation:
  enabled: false
  # payerstolog: [248,371,444]

  ## Thirdparties
  # Set configurations for third party applications in this section
thirdParties:
  dynatraceVersionDetection:
    enabled: true
