---
apiVersion: v1
kind: Secret
metadata:
  name: eo-keys-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: hzp
type: Opaque
stringData:
  cipher-key: {{ randAlphaNum 32 | b64enc | quote }}
  eo-key-1: {{ .Files.Get "files/hzp_dev.pub" | b64enc | quote }}
  eo-key-2: {{ .Files.Get "files/hzp_prod.pub" | b64enc | quote }}

