# Global values (needs to be replicated here because a subchart can't have a dependency on its parent)
global:
  imagePullSecrets:
    - docker-secret
  ingress:
    fqdn: localhost
  eoName: "NativeEdge Orchestrator"
  vault:
    host: "http://edgevault.{{ .Release.Namespace }}.svc.cluster.local"
    port: "8200"
  notification:
    smoketestEnabled: false
  istio:
    deploy: true
    ingressgateway:
      internal: true
  nginx_gw:
    enabled: false
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
  instrumentation:
    enabled: false
components:
  notification-svc:
    image: notification-svc
    version: latest
    project: hzp/
  busybox:
    image: busybox
    version: 1.37.0
    project: ''
  notification-smoke-test:
    image: notification-smoke-test
    version: latest
    project: hzp/
# Subchart values
svc:
  name: &serviceName hzp-notification-svc
  replicaCount: 1
  port: 8080
  image:
    name: notification-svc
    pullPolicy: Always
    tag: latest
  podLabels:
    hzp-app: *serviceName
    hzp-role: eo-service
    hzp.iam.webhook/active: "true"
    hzp.iam.webhook/bootstrap: "true"
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 5m
      memory: 50Mi
  env:
    - name: LOG_LEVEL
      value: "info"
    - name: WS_PONG_TIMEOUT
      value: "120"
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: create-postgres-host-configmap
          key: postgresHost
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: create-postgres-host-configmap
          key: postgresPort
    - name: DB_USER
      value: "hzp_notification_svc"
    - name: DB_PA
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: hzp_notification_svc-password
    - name: APPROLE_ID
      valueFrom:
        secretKeyRef:
          name: hzp-notification-svc-vault-secret
          key: role-id
          optional: false
    - name: APPROLE_SECRET_ID
      valueFrom:
        secretKeyRef:
          name: hzp-notification-svc-vault-secret
          key: secret-id
          optional: false
    - name: APPROLE_ID_PATH
      value: "eo-approle"
    - name: AUTH_CLIENT_ID
      value: "hzp-notification-svc"
    - name: VAULT_CERTS_KV_MOUNT_POINT
      value: "kv/m2m/hzp-notification-svc"

test:
  # Subchart values
  enabled: false
  testsuite: test-suites/smoke.xml
  replicaCount: 1
  image:
    name: notification-smoke-test
    pullPolicy: Always
    tag: latest
  podLabels:
    hzp.iam.webhook/active: "false"
    hzp-app: hzp-notification-svc-regression
    hzp-role: smoke-test
  env:
    - name: DATABASE_URL
      valueFrom: 
        configMapKeyRef:
          name: create-postgres-host-configmap
          key: postgresUrl
    - name: DATABASE_USERNAME
      value: "test"
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: test-password
  cpu: 0.25
  memory: 512Mi
  notification:
    service:
      fullname: *serviceName
      port: 80
  qtest:
    regressionProjectId: 181
    regressionContainerId: 869483
  reportportal:
    rpendpoint: 100
    rpuuid: 9bgc
    eourl: 100
    manifest: 1
    runid: 1
    release: 1
    suite: 1
