global:
  registry: "702886132326.dkr.ecr.eu-west-1.amazonaws.com"
  postgres:
    internal:
    host:
    password:

# Postgres initialization job configuration
postgres:
  enabled: 
  name:
  prefix:
  dbName:  # The db username is the same as the db name by design
image:
  imagePullSecrets:
    - name: docker-secret

hzputil:
  image: "eo-images/hzp-util"
  tag: 0.1.3
