apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
   {{- with .Values.service.annotations }}
     {{- toYaml . | nindent 4 }}
   {{- end }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: nginx-80-8080
  selector:
    app: {{ include "microservice.fullname" . }}
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}-tls
  namespace: {{ .Release.Namespace | quote }}
  annotations:
   {{- with .Values.tlsService.annotations }}
     {{- toYaml . | nindent 4 }}
   {{- end }}
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8043
      name: nginx-443-443
  selector:
    app: {{ include "microservice.fullname" . }}
  type: {{ .Values.tlsService.type }}
---
{{- if .Values.mtlsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}-mtls
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- with .Values.mtlsService.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ include "microservice.fullname" . }}
spec:
  type: {{ .Values.mtlsService.type }}
  allocateLoadBalancerNodePorts: {{ .Values.mtlsService.allocateLoadBalancerNodePorts }}
  selector:
    app: {{ include "microservice.fullname" . }}
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8043
  externalTrafficPolicy:  {{ .Values.mtlsService.externalTrafficPolicy }}
{{- end }}
---
{{- if .Values.global.ip_mode }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}-nodeport
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "microservice.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "microservice.fullname" . }}
  ports:
  - name: https
    nodePort: {{ .Values.nodePort }}
    port: 443
    protocol: TCP
    targetPort: 8043
{{- end }}
