annotations:
  imagetag: latest
apiVersion: v2
appVersion: latest
dependencies:
- condition: global.fido.deploy
  name: fido-owner
  repository: ""
  version: 0.1.0
- condition: global.fidoRv.deploy
  name: fido-rv
  repository: ""
  version: 0.1.0
- condition: global.fidoManufacturer.deploy
  name: fido-manufacturer
  repository: ""
  version: 0.1.0
- condition: global.catalogSvc.deploy
  name: hzp-catalog-svc
  repository: ""
  version: 0.1.0
- condition: global.eventSvc.deploy
  name: hzp-event-svc
  repository: ""
  version: 0.1.0
- condition: global.healthCheckSvc.deploy
  name: hzp-health-check-svc
  repository: ""
  version: 0.1.0
- condition: global.dataCollectionSvc.deploy
  name: hzp-datacollection-svc
  repository: ""
  version: 0.1.0
- condition: global.inventorySvc.deploy
  name: hzp-inventory
  repository: ""
  version: 0.1.0
- condition: global.jobSvc.deploy
  name: hzp-job-svc
  repository: ""
  version: 0.1.0
- condition: global.oeTemplateMgr.deploy
  name: hzp-oe-template-mgr
  repository: ""
  version: 0.1.0
- condition: global.smokeTest.deploy
  name: smoke-test
  repository: ""
  version: 0.1.0
- condition: global.iamProxyTest.deploy
  name: hzp-iam-proxy-test
  repository: ""
  version: 0.1.0
- condition: global.eceAgentTest.deploy
  name: ece-agent-test
  repository: ""
  version: 0.1.0
- condition: global.upgradeSvc.deploy
  name: hzp-upgrade-svc
  repository: ""
  version: 0.1.0
- condition: global.eoProxy.deploy
  name: hzp-eo-proxy
  repository: ""
  version: 0.1.0
- condition: global.recoverySvc.deploy
  name: hzp-recovery-svc
  repository: ""
  version: 0.1.0
- condition: global.certificateSvc.deploy
  name: hzp-certificate-svc
  repository: ""
  version: 0.1.0
- condition: global.eceFirmwareUpdateSvc.deploy
  name: hzp-ece-firmwareupdate-svc
  repository: ""
  version: 0.1.0
- condition: global.fruCruSvc.deploy
  name: hzp-fru-cru-svc
  repository: ""
  version: 0.1.0
- condition: global.ingressAuthzSvc.deploy
  name: hzp-ingress-authz-svc
  repository: ""
  version: 0.1.0
- condition: global.timeSvc.deploy
  name: hzp-time-svc
  repository: ""
  version: 0.1.0
- condition: global.eoInitializationSvc.deploy
  name: hzp-eo-initialization-svc
  repository: ""
  version: 0.1.0
- condition: global.productSvc.deploy
  name: hzp-product-svc
  repository: ""
  version: 0.1.0
- condition: global.eventDisplay.deploy
  name: hzp-event-display
  repository: ""
  version: 0.1.0
- condition: global.rulesSvc.deploy
  name: hzp-rules-svc
  repository: ""
  version: 0.1.0
- condition: global.computeSvc.deploy
  name: hzp-compute-svc
  repository: ""
  version: 0.1.0
- condition: global.schedulerSvc.deploy
  name: hzp-scheduler-svc
  repository: ""
  version: 0.1.0
- condition: global.iamSessionSvc.deploy
  name: hzp-iam-session-svc
  repository: ""
  version: 0.1.0
- condition: global.notification.deploy
  name: hzp-notification-svc
  repository: ""
  version: 0.1.0
- condition: global.tagsSvc.deploy
  name: hzp-tags-svc
  repository: ""
  version: 0.1.0
- condition: global.attestationSvc.deploy
  name: hzp-attestation-svc
  repository: ""
  version: 0.1.0
- condition: global.apiGateway.deploy
  name: hzp-api-gateway-svc
  repository: ""
  version: 0.1.0
- condition: global.metricsSvc.deploy
  name: hzp-metrics-svc
  repository: ""
  version: 0.1.0
description: Helm chart for Edge-Orchestrator services
name: edge-orchestrator-services
type: application
version: 1.0.0-0-2328
