{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fusion-services.name" . }}-secrets-envvars
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
data:
  REST_PROTOCOL: {{ .Values.entrypoint.protocol | quote}}
  REST_HOST: {{ .Values.entrypoint.name | quote}}
  REST_PORT: {{ .Values.entrypoint.port | quote }}
  {{ range $key, $value := .Values.secrets.env -}}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{ end -}}
{{- end }}
