{{- if .Values.secrets.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secrets
  name: {{ template "fusion-services.name" . }}-secrets
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
spec:
  replicas: {{ .Values.secrets.replicas }}
  selector:
    matchLabels:
      app: secrets
  template:
    metadata:
      labels:
        app: secrets
      {{ with .Values.secrets.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        {{- include "fusion-services.merge" ( list .Values.commonAnnotations .Values.secrets.podAnnotations ) | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      nodeSelector: {{- include "fusion-services.nodeSelector" ( list .Values.secrets $ )| trim | nindent 8 }}
      tolerations: {{- include "fusion-services.tolerations" ( list .Values.secrets $ ) | trim | nindent 8 }}
      affinity: {{- include "fusion-services.affinity" ( list .Values.secrets $ ) | trim | nindent 8 }}
      initContainers:
        - name: db-wait
          image: {{ include "fusion-services.image.name" (dict "svc" ( index .Values.components "fusion-manager-restservice") "repo" .Values.global.repository) }}
          imagePullPolicy: {{ default .Values.global.image.pullPolicy ( index .Values.components "fusion-manager-restservice" ).pullPolicy }}
          env:
            {{- include "fusion-services.postgres_env_vars" (dict "dbRoot" .Values.secrets "root" $) | nindent 12 }}
            {{- include "fusion-services.restservice_keys" . | nindent 12 }}
          command:
            - /usr/bin/env
            - -S
            - bash
            - -exuc
            - |
              python -m manager_rest.configure_manager --db-wait {{ .Values.secrets.db.host | default .Values.db.host }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{ .Values.secrets.initContainerSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.secrets.initContainerSecurityContext.runAsGroup }}
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: 256Mi
              cpu: "0.1"
            limits:
              memory: 512Mi
              cpu: "1"
        - name: secrets-migrate-db
          image: {{ include "fusion-services.image.name" (dict "svc" ( index .Values.components "fusion-manager-secrets-service" ) "repo" .Values.global.repository) }}
          imagePullPolicy: {{ default .Values.global.image.pullPolicy ( index .Values.components "fusion-manager-secrets-service" ).pullPolicy }}
          env:
            {{- include "fusion-services.postgres_env_vars" (dict "dbRoot" .Values.secrets "root" $) | nindent 12 }}
          command:
            - /usr/bin/env
            - -S
            - bash
            - -exuc
            - |
              cd /opt/manager/migrations
              alembic upgrade head
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: {{ .Values.secrets.initContainerSecurityContext.runAsUser }}
            runAsGroup: {{ .Values.secrets.initContainerSecurityContext.runAsGroup }}
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: 256Mi
              cpu: "0.1"
            limits:
              memory: 512Mi
              cpu: "1"
      containers:
        - name: secrets
          image: {{ include "fusion-services.image.name" (dict "svc" ( index .Values.components "fusion-manager-secrets-service" ) "repo" .Values.global.repository) }}
          imagePullPolicy: {{ default .Values.global.image.pullPolicy ( index .Values.components "fusion-manager-secrets-service" ).pullPolicy }}
          env:
            {{- if (.Values.secrets.eventing).stream_url }}
            - name: NATS_URL
              value: {{ tpl .Values.secrets.eventing.stream_url $ | quote}}
            {{- else if (.Values.nats).enabled }}
            - name: NATS_URL
              value: "nats://jetstream.{{ .Release.Namespace }}.svc.cluster.local:4222"
            {{- end }}
            - name: FUSION_AUTH_PSK
              valueFrom:
                secretKeyRef:
                  name: {{ template "fusion-services.name" . }}-auth-signing
                  key: psk
            {{- include "fusion-services.s3_env_vars" . | nindent 12 }}
            {{- include "fusion-services.postgres_env_vars" (dict "dbRoot" .Values.secrets "root" $) | nindent 12 }}
            {{- include "fusion-services.eo_env_vars" . | nindent 12 }}
            {{/* TODO: replace any reference to Values.rest_service.* with Values.secrets.* */}}
            - name: DEFAULT_SECRETS_BACKEND
              value: {{ tpl .Values.rest_service.config.manager.default_secrets_backend . }}
            {{- include "fusion-services.restservice_keys" . | nindent 12 }}
            {{- include "fusion-services.vault_env_vars" . | nindent 12 }}
            - name: VAULT_SECRET_PATH
              value: {{ tpl .Values.secrets.vaultSecretPath $ }}
            - name: LOGGING_LEVEL_CONFIGURATION_PATH
              value: {{ tpl .Values.secrets.logging.configMountPath $}}
            - name: LOGGING_LEVEL_GLOBAL_PATH
              value: {{ tpl .Values.secrets.logging.configMountPath $ }}/{{ tpl .Values.secrets.logging.globalConfigFile $ }}
            - name: LOGGING_LEVEL_SERVICE_PATH
              value: {{ tpl .Values.secrets.logging.configMountPath $ }}/{{ tpl .Values.secrets.logging.serviceConfigFile $ }}
            {{- if (.Values.secrets.logging).audit_logs_subject }}
            - name: AUDIT_LOGS_SUBJECT
              value: {{ tpl .Values.secrets.logging.audit_logs_subject $ | quote }}
            {{- end }}
            {{- if (.Values.global).useHzpMultitenancy }}
            - name: "HZP_MULTITENANCY"
              value: "true"
            {{- end }}
          volumeMounts:
            - name: logging
              mountPath: {{ tpl .Values.secrets.logging.configMountPath $ }}
              readOnly: true
            - name: vault-secret
              mountPath: {{ tpl .Values.secrets.vaultSecretPath $ }}
              readOnly: true
          ports:
            - containerPort: {{ .Values.secrets.port }}
          envFrom:
            - configMapRef:
                name: {{ template "fusion-services.name" . }}-secrets-envvars
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources: {{- toYaml .Values.secrets.resources | nindent 12 }}
          {{- if .Values.secrets.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              port: {{ .Values.secrets.port}}
              path: /health
            initialDelaySeconds: {{ .Values.secrets.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.secrets.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.secrets.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.secrets.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.secrets.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.secrets.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              port: {{ .Values.secrets.port}}
              path: /health
            initialDelaySeconds: {{ .Values.secrets.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.secrets.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.secrets.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.secrets.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.secrets.probes.readiness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
      {{- include "fusion-services.images.pullSecrets" . | nindent 6 }}
      volumes:
        - name: logging
          configMap:
            name: {{ include "fusion-loglevel-configmap.name" $ }}
        - name: vault-secret
          secret:
            secretName: {{ .Values.vault.componentName }}-vault-secret
{{- end }}
