{{- if .Values.secrets.enabled -}}
{{- $hook_annotations := dict "helm.sh/hook" "post-upgrade" "helm.sh/hook-weight" "-6" "helm.sh/hook-delete-policy" "before-hook-creation" }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: secrets
  name: {{ template "fusion-services.name" . }}-secrets-migrate-db
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations $hook_annotations ) | nindent 4 }}
spec:
  backoffLimit: 5
  parallelism: 1
  template:
    metadata:
      labels:
        app: secrets
      {{ with .Values.secrets.dbMigrator.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        {{- include "fusion-services.merge" ( list .Values.commonAnnotations ((.Values.secrets).dbMigrator).podAnnotations ) | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: {{ .Values.secrets.migrateDbJobSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.secrets.migrateDbJobSecurityContext.runAsGroup }}
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      nodeSelector: {{- include "fusion-services.nodeSelector" ( list .Values.secrets $ )| trim | nindent 8 }}
      tolerations: {{- include "fusion-services.tolerations" ( list .Values.secrets $ ) | trim | nindent 8 }}
      affinity: {{- include "fusion-services.affinity" ( list .Values.secrets $ ) | trim | nindent 8 }}
      containers:
        - name: secrets-db-migrator
          image: {{ include "fusion-services.image.name" (dict "svc" ( index .Values.components "fusion-manager-secrets-service" ) "repo" .Values.global.repository) }}
          imagePullPolicy: {{ default .Values.global.image.pullPolicy ( index .Values.components "fusion-manager-secrets-service" ).pullPolicy }}
          command:
            - /usr/local/bin/python
            - -m
            - service.db_migrator.migrate
          env:
            {{- include "fusion-services.vault_env_vars" . | nindent 12 }}
            {{- include "fusion-services.postgres_env_vars" (dict "dbRoot" .Values.secrets "root" $) | nindent 12 }}
            {{- include "fusion-services.postgres_env_vars" (dict "dbRoot" .Values.secrets.dbMigrator "root" $ "envPrefix" "SRC_") | nindent 12 }}
            - name: VAULT_SECRET_PATH
              value: {{ tpl .Values.secrets.vaultSecretPath $ }}
            - name: LOGGING_LEVEL_CONFIGURATION_PATH
              value: {{ tpl .Values.secrets.logging.configMountPath $}}
            - name: LOGGING_LEVEL_GLOBAL_PATH
              value: {{ tpl .Values.secrets.logging.configMountPath $ }}/{{ tpl .Values.secrets.logging.globalConfigFile $ }}
            - name: LOGGING_LEVEL_SERVICE_PATH
              value: {{ tpl .Values.secrets.logging.configMountPath $ }}/{{ tpl .Values.secrets.logging.serviceConfigFile $ }}
          volumeMounts:
            - name: logging
              mountPath: {{ tpl .Values.secrets.logging.configMountPath $ }}
              readOnly: true
            - name: vault-secret
              mountPath: {{ tpl .Values.secrets.vaultSecretPath $ }}
              readOnly: true
          envFrom:
            - configMapRef:
                name: {{ template "fusion-services.name" . }}-secrets-envvars
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources: {{- toYaml .Values.secrets.resources | nindent 12 }}
      restartPolicy: OnFailure
      {{- include "fusion-services.images.pullSecrets" . | nindent 6 }}
      volumes:
        - name: logging
          configMap:
            name: {{ include "fusion-loglevel-configmap.name" $ }}
        - name: vault-secret
          secret:
            secretName: {{ .Values.vault.componentName }}-vault-secret
{{- end }}
