{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fusion-services.name" . }}-secrets
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.secrets.port }}
  selector:
    app: secrets
  type: ClusterIP
{{- end }}
