apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fileserver.name" . }}-templates
  annotations:
    {{- include "common.annotations" ( list $ .Values.commonAnnotations ) | nindent 4 }}
data:
{{ (tpl (.Files.Glob "files/templates/*").AsConfig .) | indent 2 }}
