{{- $name := "create-fileserver-auth-secret-job"}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}
  labels:
    {{- tpl (toYaml .Values.job.podLabels) . | replace "'" "" | nindent 8 }}
{{- if .Values.job.annotations }}
  annotations:
{{ toYaml .Values.job.annotations | indent 4 }}
{{- end }}
spec:
  template:
    metadata:
      labels:
{{- tpl (toYaml .Values.job.podLabels) . | replace "'" "" | nindent 8 }}
    spec:
      # volumes:
      #   - name: htpasswd-storage
      #     emptyDir: {}
      restartPolicy: Never
      {{- include "images.pullSecrets" . | nindent 6 }}
      initContainers:
      - name: init-fusion-servives
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "hzp-util" ) "repo" .Values.global.repository) }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
          allowPrivilegeEscalation: false
        command:
          - sh
          - -c
          - |
            echo 'Waiting for Fusion Servives to become ready...'
            url="{{ tpl .Values.fusion.secretsSvc.url . }}/api/v3.1/secrets/types"
            retry_delay=10
            while true; do 
              resp_code=$(curl -s -u "admin:admin" -o /dev/null -w "%{http_code}" -H "Tenant: {{ .Values.fusion.secretsSvc.tenant }}" "$url")
              if [ "$resp_code" -eq 200 ]; then
                echo "HTTP Response Code: $resp_code - Service is available."
                break;
              fi;

              echo "HTTP Response Code: $resp_code - Service Unavailable. Retrying in $retry_delay seconds..."
              sleep "$retry_delay"
            done;
            echo 'Fusion Servives OK ✓'
      containers:
      - name: publish-fileserver-auth-secret-container
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "hzp-util" ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
          runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
          allowPrivilegeEscalation: false
        command:
          - sh
          - -c
          - |
            set -e
            echo 'Publishing fileserver auth to secrets service...'
            auth_key="public-fileserver-auth"
            secrets_api_prefix="{{ tpl .Values.fusion.secretsSvc.url . }}/api/v3.1/secrets"
            credentials="admin:admin"
            tenant="{{ .Values.fusion.secretsSvc.tenant }}"
            filer_password=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
            fileserver_auth=$(printf %s:%s {{ .Values.seaweedfs.filer.username }} $filer_password | base64)

            secret_schema=$(curl -s -u $credentials -H "Tenant: $tenant" -H "Content-Type: application/json" $secrets_api_prefix/types | jq -c '.items[] | select(.type == "password") | .schema')

            request_body=$(printf '{"display_name":"%s","type":"password","schema":%s,"value":"%s","description":"The credentials for the public file server","visibility":"tenant","is_hidden_value":false,"generated":false}' "$auth_key" "$secret_schema" "$fileserver_auth")
            http_status=$(curl -s -u $credentials -H "Tenant: $tenant" -H "Content-Type: application/json" -X PUT -o /dev/null -w "%{http_code}" $secrets_api_prefix/$auth_key -d "$request_body")

            if [ "$http_status" -eq 201 ]; then
              echo 'Publishing fileserver auth OK ✓'
            elif [ "$http_status" -eq 409 ]; then
              echo 'Publishing fileserver auth already exists OK ✓'
            else
                echo "Status code not handled (HTTP status code: $http_status)"
                exit 1
            fi
