{{- $ca := genCA "CA" 36500 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.proxyConfig.initCertSecretName }}
data:
  INIT_CA_CERT: {{ $ca.Cert | b64enc }}
  INIT_CA_KEY: {{ $ca.Key | b64enc }}
