{{- if .Values.global.dockerSecret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.global.dockerSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.dockerSecret.dockerconfigjson }}
{{- end }}
