apiVersion: v1
kind: ServiceAccount
metadata:
  name: infra-status-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infra-status-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["infra-status-config"]
  verbs: ["get", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infra-status-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: infra-status-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: infra-status-role
  apiGroup: rbac.authorization.k8s.io
