user  nginx;
include /etc/nginx/conf.d/workers.vars;

error_log  /var/log/nginx/error.log warn;
pid        /tmp/nginx.pid;

env FUSION_AUTH;

http {
    lua_shared_dict lua_cache 1m;
    server_tokens       off;
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;
    sendfile_max_chunk  1m;

    log_format main '[$time_local] $remote_addr[$upstream_cache_status] -> $upstream_addr '
                    '"$request" "$http_connection" $status $body_bytes_sent '
                    'upstream_response_time=$upstream_response_time '
                    'request_length=$request_length upstream_request_length=$upstream_http_content_length '
                    'range=$http_range upstream_range=$upstream_http_range';

    access_log  /var/log/nginx/access.log  main;

    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5:!AES256-GCM-SHA384:!AES256-SHA256:!AES256-SHA:!CAMELLIA256-SHA:!ECDHE-RSA-AES256-SHA:!ECDHE-RSA-AES128-SHA:!AES128-GCM-SHA256:!AES128-SHA256:!AES128-SHA:!CAMELLIA128-SHA;

    sendfile        on;

    # CIS 5.2.3
    large_client_header_buffers 4 8k;

    # CIS 5.2.1
    client_body_timeout     120s;
    client_header_timeout   120s;

    keepalive_timeout  100;

    proxy_connect_timeout 330s;
    proxy_send_timeout 330s;
    proxy_read_timeout 330s;

    add_header Referrer-Policy same-origin always;
    add_header X-Content-Type-Options "nosniff" always;

    proxy_cache_path /data/nginx/cache levels=1:2 keys_zone=cache:300m max_size=10g inactive=6m use_temp_path=off;
    include /etc/nginx/conf.d/*.conf;
}
