# Global values (needs to be replicated here because a subchart can't have a dependency on its parent)
global:
  repository: isgedge.artifactory.cec.lab.emc.com/isgedge-docker-virtual/
  project: hzp/
  imagePullSecrets:
    - docker-secret
  keycloak:
    scheme: http
    host: keycloak-http
    port: "80"
  attestationSvc:
    smoketestEnabled: false
  clusterResourcesPrefix: ""
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
  instrumentation:
    enabled: false
components:
  attestation-svc:
    image: attestation-svc
    version: latest
    project: hzp/
  busybox:
    image: busybox
    version: 1.37.0
    project: ''
# Subchart values
svc:
  name: &serviceName hzp-attestation-svc
  publicKeysProvider: http://localhost:8080
  port: 8080
  replicaCount: 1
  rbac:
    name: attestation-rbac
    clusterRole: attestation-role
    clusterRoleBinding: attestation-access
  image:
    name: attestation-svc
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 25Mi
  podLabels:
    hzp-app: *serviceName
    hzp-role: eo-service
    hzp.attestation.webhook/active: "true"
    hzp.iam.webhook/active: "{{ .Values.global.nginx_gw.enabled | quote }}"
  podAnnotations:
    hzp.attestation.webhook/authn-public-keys-path: '{{ .Values.svc.publicKeysProvider }}'
    hzp.attestation.webhook/authentication-enabled: "true"
    hzp.attestation.webhook/authorization-enabled: "true"
    hzp.iam.webhook/authentication-enabled: "false"
    hzp.iam.webhook/authorization-enabled: "false"
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  env:
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: create-postgres-host-configmap
          key: postgresHost
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: create-postgres-host-configmap
          key: postgresPort
    - name: DB_USER
      value: "hzp_attestation_svc"
    - name: DB_PA
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: hzp_attestation_svc-password
    - name: ORG_ID
      valueFrom:
        secretKeyRef:
          name: mist-org-secret
          key: org-id
    - name: ORG_NAME
      valueFrom:
        secretKeyRef:
          name: mist-org-secret
          key: org-name

autoscaling:
  # The minimum and maximum number of replicas for the Deployment
  minReplicas: 1
  maxReplicas: 1
  # The metrics to use for scaling
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  # The scaling policy to use. This will scale up quickly but only scale down a single Pod per 5 minutes.
  # This is important because caches are usually only replicated to 2 Pods and if one of those Pods is terminated this will give the cluster time to recover.
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300

dbchecker:
  image:
    # Docker image used to check Postgresql readiness at startup
    repository: busybox
    # Image tag for the dbchecker image
    tag: 1.37.0
    # Image pull policy for the dbchecker image
    pullPolicy: IfNotPresent
  # SecurityContext for the dbchecker container
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
  # Resource requests and limits for the dbchecker container
  resources:
    requests:
      cpu: "20m"
      memory: "32Mi"
    limits:
      cpu: "20m"
      memory: "32Mi"

database:
  existingSecret: postgres-secret
  hostname: postgres
  port: 5432
  
