apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "registry.name" . }}-config
  labels:
    app.kubernetes.io/app: {{ template "registry.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ template "registry.name" . }}-instance
    app.kubernetes.io/managed-by: helm
data:
  config.yml: |-
{{ toYaml .Values.configData | indent 4 }}
