# In some cases, this subchart is required to be deployed without this job
{{- if or (.Values.global.regressionEnabled) (.Values.global.smokeTest.runJob) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: eo-smoke-test
spec:
  template:
    metadata:
      name: eo-smoke-test
      labels:
{{- tpl (toYaml .Values.test.podLabels) . | replace "'" "" | nindent 8 }}
    spec:
      {{- include "images.pullSecrets" . | nindent 6 }}
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.test $ )| trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.test $ ) | trim | nindent 8 }}
      affinity: {{- include "pods.affinity" ( list .Values.test $ ) | trim | nindent 8 }}
      containers:
      {{- if .Values.global.eoTest }}
      - image: "{{ .Values.test.image.repository  | default (include "global.repo" .) }}{{ .Values.global.eoTest.image }}:{{ .Values.test.image.tag | default .Chart.Annotations.imagetag }}"
      {{- else }}
      - image: "{{ .Values.test.image.repository  | default (include "global.repo" .) }}{{ .Values.test.image.name }}:{{ .Values.test.image.tag | default .Chart.Annotations.imagetag }}"
      {{- end }}
        name: eo-smoke-test-container
        volumeMounts:
        - mountPath: /data
          name: data-volume
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: BASE_URL
            value: "http://{{ .Values.test.eventsvc.service.fullname }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: FRU_CRU_SVC_BASE_URL
            value: "http://{{ .Values.test.frucrusvc.service.fullname }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: INVENTORY_SVC_BASE_URL
            value: "http://{{ .Values.test.inventory.service.fullname }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: ONBOARDING_SVC_BASE_URL
            value: "http://{{ .Values.test.fidoOnboarding.service.fullname }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: EDGE_VAULT_URL
            value: "http://edgevault.{{ .Release.Namespace }}.svc.cluster.local:8200"
          - name: EO_IP
            value: {{ .Values.global.ingress.fqdn }}
          - name: RP_ENDPOINT
            value: "{{ .Values.test.reportportal.rpendpoint }}"
          - name: RP_API_KEY
            value: "{{ .Values.test.reportportal.rpuuid }}"
          - name: RP_MODE
            value: default
          - name: RP_PROJECT
            value: HZP_EO_SERVICES
          - name: RP_LAUNCH
            value: "EO-regression-tests"
          - name: RP_ATTRIBUTES
            value: "RELEASE_VERSION:{{ .Values.test.reportportal.release }};EO_IP:{{ .Values.test.reportportal.eourl }};EO_MANIFEST:{{ .Values.test.reportportal.manifest }};ECE_MANIFEST:{{ .Values.test.reportportal.ecemanifest }};TEST_GROUP:{{ .Values.test.reportportal.suite }};RP_LAUNCH_KEY_ATTRIBUTE:{{ .Values.test.reportportal.runid }};;RELEASE_VERSION:{{ .Values.test.reportportal.release }};"
          {{- toYaml .Values.test.env | nindent 10 }}
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command: ['/bin/sh', '-c']
        # Sleep before test to allow netpol and istio-proxy to take effect
        args:
          - |
            sleep 60; echo All dependent components are running. Start testing!;
            echo "${NODE_IP} default.dell.com rv.dell.com rv.local.edge rv1.local.edge rv2.local.edge rv.internal.use.only rendezvous mtls.edge.internal.use.only" >> /etc/hosts;
            java -jar tests.jar {{ .Values.test.testsuite }}; sleep 60;
            if wget -q --post-data='' -S -O /dev/null http://127.0.0.1:15020/quitquitquit 2>/dev/null; then
                echo "Terminated istio-proxy."
            fi
      volumes:
      - name: data-volume
        hostPath:
          path: /data/
      initContainers:
      - name: init-keycloak
        image: "{{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}"
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command: ['sh', '-c', "until nslookup keycloak-http.{{ .Release.Namespace }}.svc.cluster.local; do echo waiting for keycloak-http; sleep 2; done"]
      - name: init-postgres
        image: "{{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}"
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for PostgreSQL to become ready...'

            until printf "." && nc -z -w 2 {{ .Values.test.postgresql.service.fullname }} {{ .Values.test.postgresql.service.port }}; do
                sleep 2;
            done;

            echo 'PostgreSQL OK ✓'
      - name: init-event-svc
        image: "{{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}"
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for Event-Svc to become ready...'

            until printf "." && nc -z -w 2 {{ .Values.test.eventsvc.service.fullname }} {{ .Values.test.eventsvc.service.port }}; do
                sleep 2;
            done;

            echo 'Hzp-event-svc OK ✓'
      - name: init-jetstream
        image: "{{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}"
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for jetstream to become ready...'

            until printf "." && nc -z -w 2 {{ .Values.test.jetstream.service.fullname }} {{ .Values.test.jetstream.service.port }}; do
                sleep 2;
            done;

            echo 'jetstream OK ✓'
      {{- if eq .Values.test.eoEceRegression true }}
      - name: init-frucru-svc
        image: "{{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}"
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for hzp-fru-cru-svc to become ready...';

            until printf "." && nc -z -w 2 {{ .Values.test.frucrusvc.service.fullname }} {{ .Values.test.frucrusvc.service.port }}; do
                sleep 2;
            done;
            echo 'hzp-fru-cru-svc OK ✓';

      - name: init-fido-onboarding-svc
        image: "{{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}"
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for fido-onboarding-svc to become ready...';

            until printf "." && nc -z -w 2 {{ .Values.test.fidoOnboarding.service.fullname }} {{ .Values.test.fidoOnboarding.service.port }}; do
                sleep 2;
            done;
            echo 'fido-onboarding-svc OK ✓';

            echo 'Waiting for fido-owner svc to become ready...';

            until printf "." && nc -z -w 2 {{ .Values.test.fidoOwner.service.fullname }} {{ .Values.test.fidoOwner.service.port }}; do
                sleep 2;
            done;
            echo 'fido-owner svc OK ✓';

      - name: init-inventory-svc
        image: "{{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}"
        imagePullPolicy: {{ .Values.test.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            echo 'Waiting for hzp-inventory-svc to become ready...';

            until printf "." && nc -z -w 2 {{ .Values.test.inventory.service.fullname }} {{ .Values.test.inventory.service.port }}; do
                sleep 2;
            done;
            echo 'hzp-inventory-svc OK ✓';
      {{- end }}
      restartPolicy: Never
{{- end }}
