global:
  registry: "702886132326.dkr.ecr.eu-west-1.amazonaws.com"
  is-saas-env: true
  staticOnPremOrgId: ""
  ingress:
    fqdn: ""
nameOverride: "dsp-iam-token-svc"
fullnameOverride: "dsp-iam-token-svc"

replicaCount: 1

# defaults are dev:
dellEnvironment: "dev"
sslCertificates: "arn:aws:acm:eu-west-1:702886132326:certificate/aa01e3eb-053d-40c7-8f00-5f70741a3b3d"
albName: "dev.sp.dell.com"
albGroupName: "saas-dsp-portal-dev"
domain: "dev.sp.dell.com"

# values that contains list of items for configmap env:
extended_list_env:
extended_list_values:


#replace values from configmap.yaml of your service
#set the configs values Hardcoded from old vluefile env values.
# ALL!!! values must be in QUOTES!!!!
config:
  configmap:


# set all the deployment envs HERE!
# secretname= global.secretname
# keyToEnvName= the name of the env-ar on the pods (dell__Secret__ConnectionStrings__dellConnectionString)
# key = the actual key needed from the secret
# u can add more then 1 secret to use(see in your value global parameter)
externalsecrets:


image:
  image: "eo-images/iam-token-svc"
  tag: "3.2.0.0-49f3f35-d90eca5c"
  pullPolicy: Always
  imagePullSecrets:
    - name: docker-secret

# set in deployment.yaml.orig (previously was hardcoded inside the deployment)
entrypoint:
  cmd: "./main"
  arg: ""
  workingDir: ""

containerPort:
  http: 8080

terminationGracePeriodSeconds: 30

lifecycle: {}

updateStrategy: {}

extraLabels: []

tokenSvc:
  issuerURL: https://dsp-portal.dev.sp.dell.com
  externalIssuerName: http://www.dell.com/identity
  externalIssuerJWKsURL: https://www-poc.dell.com/di/v3/fp/v3/keys/public

extraEnvs:
  - name: APP_PORT
    value: "8080"
  - name: EVENTING_TYPE
    value: "noop"
  - name: IAM_SVC_URL
    value: http://dsp-iam-mgmt-svc
  - name: ASSET_SVC_URL
    value: http://dsp-portal-infra-svc

startupProbe:
  httpGet:
    path: /admin/health/dependency
    port: 14000
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /admin/health/liveness
    port: 14000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /admin/health/dependency
    port: 14000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 20
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

volumeMounts:

deployment:
  enabled: true

# previus hardcoded in deployment.yaml.orig
# now we can set dell.prod for pproduction apps (as for now all apps are dell.local)
# dnsConfig:
#   searches:

service:
  enabled: true
  type: ClusterIP
  labels: []
  http:
    port: 80
    targetPort: 8080
    nodePort: null
  #Only if you need one service to listen to two ports (Better to split that service to 2 mircoservices.)
  #Must be used with Multiple ingress paths.
  multiPortService:
    enabled: false
    http:
      port: 4999
      name: external
      targetPort: null

ingress:
  enabled: false
  #ALB Annotations: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#annotations
  annotations: {}
  hosts:
    - path: /
      pathType: ImplementationSpecific

  multipath:
    enabled: true
    hosts:
      - paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              # serviceName: app1-service
              servicePort: 8080

# Whether or not we want a pod disruption budget, enabled by default, but this only is enabled if replicaCount > 1
podDistuptionBudget:
  enabled: true
  minAvailable: 1

resources:
  limits:
    cpu: "50m"
    memory: "200Mi"
  requests:
    cpu: "5m"
    memory: "25Mi"


# we should use only HPA OR Keda.
# if keda is needed plz use keda as the cpu\mem scaler
autoscaling: # Only one can be enabled
  minReplicas: 1
  maxReplicas: 3
  hpa:
    enabled: true
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            averageValue: 50m
            type: Utilization
      - type: Resource
        resource:
          name: memory
          target:
            averageValue: 200Mi
            type: Utilization


# criticalinfra = all our criticalinfra apps (namespace criticalinfra)
# infrastructure = internal tools(like devtools apps)
# dell = rest of dell microservices (exclude criticalinfra)
# only 1 selector will be selected!!
nodeSelector: {}
# kubernetes.io/os: linux


# The folowing property is mandetory only for critical infra!!!
# tolerations: {}
tolerations: {}
  # - key: "app"
  #   operator: "Equal"
  #   value: "dell"
  # - key: "app"
#   operator: "Equal"
#   value: "dell-prod"

volumes:

podAntiAffinity:
  enabled: false

topologySpreadConstraints: {}



# Create serviceaccount for the service
serviceAccount:
  enabled: true
  annotations: {}
  # Here's an example of assigning an IAM role to a pod
  # eks.amazonaws.com/role-arn: arn:aws:iam::123123123:role/role-name-goes-here

#Commit: DEVOPS-5837-FR-Hashmaps
hashcalculation:
  enabled: false
  # payerstolog: [248,371,444]

  ## Thirdparties
  # Set configurations for third party applications in this section
thirdParties:
  dynatraceVersionDetection:
    enabled: true
