{{- if .Values.mgmtworker.access.localCluster }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fusion-services.name" . }}-mgmtworker-serviceaccount
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fusion-services.name" . }}-mgmtworker-role
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "create", "get", "watch", "list", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fusion-services.name" . }}-mgmtworker-binding
  annotations:
    {{- include "fusion-services.merge" ( list .Values.commonAnnotations "" ) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "fusion-services.name" . }}-mgmtworker-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fusion-services.name" . }}-mgmtworker-role
{{- end }}
