apiVersion: v1
data:
  di-auth-client-password: {{ .Values.di.clientPwd | b64enc }}
  di-auth-client-name: {{ .Values.di.clientId | b64enc }}
kind: Secret
metadata:
  name: di-client-secret
  namespace: {{ .Release.Namespace }}