{{- if or (.Values.global.regressionEnabled) (.Values.global.iamProxyTest.smoketestEnabled) }}
{{- $test := .Values.test -}}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $test.svc.name }}
spec:
  template:
    spec:    
      {{- include "images.pullSecrets" . | nindent 6 }}
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.test $ )| trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.test $ ) | trim | nindent 8 }}
      affinity: {{- include "pods.affinity" ( list .Values.test $ ) | trim | nindent 8 }}
      containers:
        - image: {{ include "manifest.image.name" (dict "name" .Values.test.svc.image.name "globals" .Values.global.components "repo" .Values.global.repository) }}
          imagePullPolicy: {{ $test.svc.image.pullPolicy }}
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: {{ $test.svc.port }}
          env:
            {{- toYaml $test.svc.env | nindent 12 }}
  {{- end }}
