# Global values (needs to be replicated here because a subchart can't have a dependency on its parent)
global:
  imagePullSecrets:
    - docker-secret
  ingress:
    fqdn: localhost
  iamProxy:
    commandDecorator:
      command:
        - sh
        - -c
        - |
          if [ "$SIDECAR_INJECTED" == "enabled" ]; then
            echo 'Waiting for sidecar proxy to become ready...'
            until printf "." && nc -z -w 2 127.0.0.1 15025; do
                sleep 2;
            done;
            echo 'Sidecar proxy is ready ✓'
            exec {{ .Values.iamProxyEntry }} &
          else
            echo 'No sidecar proxy detected ✓'
            exec {{ .Values.iamProxyEntry }} &
          fi
          pid=$!
          trap 'kill -SIGTERM $pid; wait $pid' SIGTERM
          wait $pid
  vault:
    host: "http://edgevault.{{ .Release.Namespace }}.svc.cluster.local"
    port: "8200"
  message:
    type: nats
  certificateSvc:
    smoketestEnabled: false

  istio:
    deploy: true
    mTLSHost: []
    mTLSHostRecovery: []
    defaultPrefix:
      mTLSHost: ""
      mTLSHostRecovery: ""
    ingressgateway:
      internal: true
  nginx_gw:
    enabled: false
  clusterResourcesPrefix: ""

  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
  instrumentation:
    enabled: false
  dsp:
    portal:
      namespace: dapp
components:
  certificate-svc:
    image: certificate-svc
    version: latest
    project: hzp/
  busybox:
    image: busybox
    version: 1.37.0
    project: ''
  kubectl:
    image: kubectl
    version: 1.30.5
    project: bitnami/
  hzp-util:
    image: hzp-util
    version: 0.1.3
    project: hzp/
  certificate-smoke-test:
    image: certificate-smoke-test
    version: latest
    project: hzp/
# Subchart values
svc:
  name: &serviceName hzp-certificate-svc
  replicaCount: 1
  port: 8080
  image:
    name: certificate-svc
    pullPolicy: Always
    tag: latest
  podLabels:
    hzp-app: *serviceName
    hzp-role: &netpolRole eo-service
    hzp.iam.webhook/active: 'true'
    hzp.iam.webhook/bootstrap: 'true'
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 5m
      memory: 25Mi
  rbac:
    namePrefix: certificate-svc
  env:
    - name: APPROLE_ID
      valueFrom:
        secretKeyRef:
          name: hzp-certificate-svc-vault-secret
          key: role-id
          optional: false
    - name: APPROLE_SECRET_ID
      valueFrom:
        secretKeyRef:
          name: hzp-certificate-svc-vault-secret
          key: secret-id
          optional: false
    - name: DB_HOST
      valueFrom:
        configMapKeyRef:
          name: create-postgres-host-configmap
          key: postgresHost
    - name: DB_PORT
      valueFrom:
        configMapKeyRef:
          name: create-postgres-host-configmap
          key: postgresPort
    - name: DB_USER
      value: "hzp_certificate_svc"
    - name: DB_PA
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: hzp_certificate_svc-password
    - name: APPROLE_ID_PATH
      value: "eo-approle"
    - name: AUTH_CLIENT_ID
      value: "hzp-certificate-svc"
    - name: VAULT_CERTS_KV_MOUNT_POINT
      value: "kv/m2m/hzp-certificate-svc"
  autoScaling:
    enabled: false
    labels: {}
    minReplicas: 1
    maxReplicas: 4
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 600
        policies:
          - type: Pods
            value: 1
            periodSeconds: 600
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
          - type: Pods
            value: 1
            periodSeconds: 60

job:
  jobAnnotations:
    "helm.sh/hook": post-install,post-upgrade
  podLabels:
    hzp-app: *serviceName
    hzp-role: *netpolRole
    hzp.iam.webhook/active: "false"
    sidecar.istio.io/inject: "false"
  resources:
    limits:
      cpu: 50m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 25Mi

migration:
  podLabels:
    hzp-app: *serviceName
    app: migrations
    hzp-role: *netpolRole
    hzp.iam.webhook/active: "false"
    sidecar.istio.io/inject: "false"
  resources:
    limits:
      cpu: 50m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 25Mi

test:
  podLabels:
    hzp-app: hzp-certificate-svc-regression
    hzp-role: smoke-test
    hzp.iam.webhook/active: "false"
  # Subchart values
  testsuite: test-suites/smoke.xml
  replicaCount: 1
  rbac:
    name: certificate-svc-test-rbac
    clusterRole: certificate-svc-test-role
    clusterRoleBinding: certificate-svc-test-access
  image:
    name: certificate-smoke-test
    pullPolicy: Always
    tag: latest
  env:
    - name: MESSAGING_URL
      value: "nats://jetstream.hzp.svc.cluster.local"
    - name: MESSAGING_STREAM_NAME
      value: "K-ORDERS"
  cpu: 0.25
  memory: 512Mi
  service:
    fullname: *serviceName
    port: 80
  qtest:
    regressionProjectId: 181
    regressionContainerId: 779767
  reportportal:
    rpendpoint: 100
    rpuuid: 9bgc
    eourl: 100
    manifest: 1
    runid: 1
    release: 1
    suite: 1

