apiVersion: v1
kind: ServiceAccount
metadata:
  name: eula-update-service-account
  namespace: {{ .Release.Namespace }}
  annotations: 
    "helm.sh/hook" : post-install,post-upgrade
    "helm.sh/hook-delete-policy" : hook-succeeded, before-hook-creation, hook-failed

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eula-update-role
  namespace: {{ .Release.Namespace }}
  annotations: 
    "helm.sh/hook" : post-install,post-upgrade
    "helm.sh/hook-delete-policy" : hook-succeeded, before-hook-creation, hook-failed
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: [ "delete" ]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: [ "get","patch" ]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["delete" ]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eula-update-role-binding
  namespace: {{ .Release.Namespace }}
  annotations: 
    "helm.sh/hook" : post-install,post-upgrade
    "helm.sh/hook-delete-policy" : hook-succeeded, before-hook-creation, hook-failed
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: eula-update-role
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: eula-update-service-account
