apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-nginx-config
data:
  nginx.conf: |
    pid /tmp/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      include mime.types;
      default_type application/octet-stream;
      sendfile on;
      keepalive_timeout 65;
      access_log /dev/stdout;
      error_log /dev/stderr;

      include /etc/nginx/conf.d/*.conf;
    }