{{ if .Values.victoriametrics.deploy }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-victoria-metrics" (include "chart.fullname" .))) }}

{{- $username := "vm" | b64enc | quote }}
{{- $password := (randAlphaNum 64) | lower | b64enc | quote }}

{{- if $secret }}
{{- $username = index $secret.data "username" }}
{{- $password = index $secret.data "password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-victoria-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: {{ $username }}
  password: {{ $password }}
{{ end }}
