{{ if .Values.victoriametrics.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-vminsert
  labels: &labels
    app: vminsert
    chart: {{ include "chart.chart" . }}
    release: {{ include "selector.label.release.name" . }}
    heritage: {{ .Release.Service }}
    hzp-app: vminsert
    hzp-role: mist-service
    hzp.iam.webhook/active: '{{ .Values.global.nginx_gw.enabled }}'
spec:
  replicas: {{ .Values.victoriametrics.vminsert.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: vminsert
      release: {{ include "selector.label.release.name" . }}
  template:
    metadata:
      annotations:
        hzp.iam.webhook/authentication-enabled: "false"
        hzp.iam.webhook/authorization-enabled: "false"
      labels: *labels
    spec:
      {{- include "images.pullSecrets" . | nindent 6 }}
      securityContext:
        runAsUser: {{ .Values.global.podSecurityContext.runAsUser }}
        fsGroup: 1000
        runAsGroup: {{ .Values.global.podSecurityContext.runAsGroup }}
        seccompProfile:
          type: RuntimeDefault
      nodeSelector: {{- include "pods.nodeSelector" ( list .Values.victoriametrics.vminsert $ )| trim | nindent 8 }}
      tolerations: {{- include "pods.tolerations" ( list .Values.victoriametrics.vminsert $ ) | trim | nindent 8 }}
      initContainers:
        - image: {{ include "manifest.image.name" (dict "data" (index .Values.components "busybox" ) "repo" .Values.global.repository) }}
          imagePullPolicy: Always
          name: init-vmstorage
          securityContext:
            runAsUser: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          command:
            - sh
            - -c
            - |
              echo 'Waiting for vmstorage to become ready...'
              until printf "." && nc -z -w 2 {{ include "chart.fullname" . }}-vmstorage 8482; do
                  sleep 2;
              done;
              echo 'mist-ee-vmstorage ready OK ✓'
      containers:
      - name: vminsert
        image: {{ include "manifest.image.name" (dict "data" (index .Values.components "mist-vminsert" ) "repo" .Values.global.repository) }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          runAsUser: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ "ALL" ]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        command:
        - /bin/sh
        - -c
        args:
        - |
          export VMUSER=$(cat /etc/vm-auth/username)
          export VMPASS=$(cat /etc/vm-auth/password)
          exec /vminsert-prod \
          -httpAuth.username=$VMUSER \
          -httpAuth.password=$VMPASS \
          --influxTrimTimestamp={{ .Values.victoriametrics.vminsert.extraArgs.influxTrimTimestamp | default "1s" }} \
          --maxConcurrentInserts={{ .Values.victoriametrics.vminsert.extraArgs.maxConcurrentInserts | default 20 }} \
          --storageNode={{ include "chart.fullname" . }}-vmstorage:8400
        resources:
          requests:
            memory: {{ .Values.victoriametrics.vminsert.resources.requests.memory | default "30Mi" }}
            cpu: {{ .Values.victoriametrics.vminsert.resources.requests.cpu | default "50m" }}
          limits:
            memory: {{ .Values.victoriametrics.vminsert.resources.limits.memory | default "300Mi" }}
            cpu: {{ .Values.victoriametrics.vminsert.resources.limits.cpu | default "1000m" }}
        volumeMounts:
          - name: vm-auth
            mountPath: /etc/vm-auth
            readOnly: true
      volumes:
        - name: vm-auth
          secret:
            secretName: {{ include "chart.fullname" . }}-victoria-metrics
{{- end }}
