apiVersion: v1
data:
  client-aot-secret: {{ .Values.aot.clientSecret | b64enc }}
  client-aot-id: {{ .Values.aot.clientId | b64enc }}
kind: Secret
metadata:
  name: aot-client-secret
  namespace: {{ .Release.Namespace }}