name: Use Custom Action
run-name: Deploy by @${{ github.actor }}
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true
  
on: 
  pull_request:
    branches:
      - 'mian'
      - '!*wtx*'
  push:
    branches:
      - '*'
  issues:
    types:
      - opened

jobs:
  hello_world_job:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Custom Action
        uses: Tianxiang6-Wang/workflow-action-poc@v2
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
