{{- if or (and .Values.filer.s3.enabled .Values.filer.s3.enableAuth (not .Values.filer.s3.existingConfigSecret)) (and .Values.s3.enabled .Values.s3.enableAuth (not .Values.s3.existingConfigSecret)) }}
{{- $secretName := (printf "%s-s3-secret" (include "seaweedfs.name" .))}}
{{- $oldSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- if or (not $oldSecret) (not $oldSecret.data) }}
{{- $oldSecret = lookup "v1" "Secret" .Release.Namespace "seaweedfs-s3-secret" }}
{{ end }}
{{- $access_key_admin := randAlphaNum 16 -}}
{{- $secret_key_admin := randAlphaNum 32 -}}
{{- $access_key_read := randAlphaNum 16 -}}
{{- $secret_key_read := randAlphaNum 32 -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "seaweedfs.name" . }}-s3-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: s3
stringData:
  {{- if or (not $oldSecret) (not $oldSecret.data) }}
  AWS_ACCESS_KEY_ID: {{ $access_key_admin }}
  AWS_SECRET_ACCESS_KEY: {{ $secret_key_admin }}
  read_access_key_id: {{ $access_key_read }}
  read_secret_access_key: {{ $secret_key_read }}
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ $access_key_admin }}","secretKey":"{{ $secret_key_admin }}"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{ $access_key_read }}","secretKey":"{{ $secret_key_read }}"}],"actions":["Read"]}]}'
  {{ else }}
  {{- $adminKey := index $oldSecret.data "admin_access_key_id" }}
  {{- if not $adminKey }}
  AWS_ACCESS_KEY_ID: {{ index $oldSecret.data "AWS_ACCESS_KEY_ID" | b64dec }}
  AWS_SECRET_ACCESS_KEY: {{ index $oldSecret.data "AWS_SECRET_ACCESS_KEY" | b64dec }}
  {{ else }}
  AWS_ACCESS_KEY_ID: {{ index $oldSecret.data "admin_access_key_id" | b64dec }}
  AWS_SECRET_ACCESS_KEY: {{ index $oldSecret.data "admin_secret_access_key" | b64dec }}
  {{ end }}
  read_access_key_id: {{ index $oldSecret.data "read_access_key_id" | b64dec }}
  read_secret_access_key: {{ index $oldSecret.data "read_secret_access_key" | b64dec }}
  seaweedfs_s3_config: {{ index $oldSecret.data "seaweedfs_s3_config" | b64dec | quote }}
  {{ end }}
  {{- if .Values.filer.s3.auditLogConfig }}
  filer_s3_auditLogConfig.json: |
    {{ toJson .Values.filer.s3.auditLogConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.s3.auditLogConfig }}
  s3_auditLogConfig.json: |
    {{ toJson .Values.s3.auditLogConfig | nindent 4 }}
  {{- end }}
{{- end }}
